package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AdtAdtDtlTbl generated by hbm2java
 */
@Entity
@Table(name = "adt_adt_dtl_tbl", schema = "public")
public class AdtAdtDtlTbl implements java.io.Serializable {

	private AdtAdtDtlTblId id;

	public AdtAdtDtlTbl() {
	}

	public AdtAdtDtlTbl(AdtAdtDtlTblId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "adtBaseTblIdent", column = @Column(name = "ADT_BASE_TBL_IDENT", length = 3)),
			@AttributeOverride(name = "adtAdtTblIdent", column = @Column(name = "ADT_ADT_TBL_IDENT", length = 3)),
			@AttributeOverride(name = "adtOnlAdtInd", column = @Column(name = "ADT_ONL_ADT_IND", length = 1)),
			@AttributeOverride(name = "adtBchAdtInd", column = @Column(name = "ADT_BCH_ADT_IND", length = 1)),
			@AttributeOverride(name = "adtBkgAdtInd", column = @Column(name = "ADT_BKG_ADT_IND", length = 1)),
			@AttributeOverride(name = "adtCrtUpdtDt", column = @Column(name = "ADT_CRT_UPDT_DT", length = 13)),
			@AttributeOverride(name = "adtUserid", column = @Column(name = "ADT_USERID", length = 101)),
			@AttributeOverride(name = "adtDelSta", column = @Column(name = "ADT_DEL_STA", length = 1)),
			@AttributeOverride(name = "branchid", column = @Column(name = "BRANCHID", length = 2)) })
	public AdtAdtDtlTblId getId() {
		return this.id;
	}

	public void setId(AdtAdtDtlTblId id) {
		this.id = id;
	}

}
