package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BccCountry generated by hbm2java
 */
@Entity
@Table(name = "bcc_country", schema = "public")
public class BccCountry implements java.io.Serializable {

	private String countryCodeEn;
	private Short countryCodeNum;
	private String countryName;
	private String currCode;
	private String timeOffset;
	private String eodTime;
	private String bodTime;
	private String intradayExeTime;
	private String processName;
	private Date processTime1;
	private Date processTime2;
	private Date processTime3;
	private String createdBy;
	private Date creationDate;
	private String verifiedBy;
	private Date verifiedDate;
	private Character deleteFlag;
	private Short versionNo;
	private String offsetSign;
	private String accrualFrequency;
	private Short clearingWindow;
	private Integer maxPdcPeriodMonth;
	private Integer directCreditCode;
	private Integer directCreditReversalCode;
	private Integer directDebitCode;
	private Integer directDebitReversalCode;
	private Date rcmsBusinessDate;
	private String useDestinationHolidays;
	private String useSourceHolidays;
	private String daylightSavingCode;
	private Integer cutoffTime;
	private String authorisedBy;
	private Date authorisedDate;
	private String firstAuthorisedBy;
	private Date firstAuthorisedDate;
	private Boolean validNtnLtyFlag;
	private Boolean validResFlag;
	private Boolean notaryFlag;
	private Boolean postalFlag;
	private Boolean nonCoopFlag;
	private Boolean ctryExstngFlag;
	private Long continentCode;
	private Long regionCode;
	private Short altCtryCodeNum;
	private Byte continent;
	private String countryNameL01;
	private String countryNameL02;
	private String countryNameL03;
	private String countryNameL04;
	private String countryNameL05;
	private Short region;
	private String isEu;
	private BigDecimal createdByUserId;
	private BigDecimal verifiedByUserId;
	private BigDecimal modifiedByUserId;
	private String modifiedBy;
	private Date modifiedDate;
	private String countryCutoffFlag;

	public BccCountry() {
	}

	public BccCountry(String countryCodeEn) {
		this.countryCodeEn = countryCodeEn;
	}

	public BccCountry(String countryCodeEn, Short countryCodeNum, String countryName, String currCode,
			String timeOffset, String eodTime, String bodTime, String intradayExeTime, String processName,
			Date processTime1, Date processTime2, Date processTime3, String createdBy, Date creationDate,
			String verifiedBy, Date verifiedDate, Character deleteFlag, Short versionNo, String offsetSign,
			String accrualFrequency, Short clearingWindow, Integer maxPdcPeriodMonth, Integer directCreditCode,
			Integer directCreditReversalCode, Integer directDebitCode, Integer directDebitReversalCode,
			Date rcmsBusinessDate, String useDestinationHolidays, String useSourceHolidays, String daylightSavingCode,
			Integer cutoffTime, String authorisedBy, Date authorisedDate, String firstAuthorisedBy,
			Date firstAuthorisedDate, Boolean validNtnLtyFlag, Boolean validResFlag, Boolean notaryFlag,
			Boolean postalFlag, Boolean nonCoopFlag, Boolean ctryExstngFlag, Long continentCode, Long regionCode,
			Short altCtryCodeNum, Byte continent, String countryNameL01, String countryNameL02, String countryNameL03,
			String countryNameL04, String countryNameL05, Short region, String isEu, BigDecimal createdByUserId,
			BigDecimal verifiedByUserId, BigDecimal modifiedByUserId, String modifiedBy, Date modifiedDate,
			String countryCutoffFlag) {
		this.countryCodeEn = countryCodeEn;
		this.countryCodeNum = countryCodeNum;
		this.countryName = countryName;
		this.currCode = currCode;
		this.timeOffset = timeOffset;
		this.eodTime = eodTime;
		this.bodTime = bodTime;
		this.intradayExeTime = intradayExeTime;
		this.processName = processName;
		this.processTime1 = processTime1;
		this.processTime2 = processTime2;
		this.processTime3 = processTime3;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.verifiedBy = verifiedBy;
		this.verifiedDate = verifiedDate;
		this.deleteFlag = deleteFlag;
		this.versionNo = versionNo;
		this.offsetSign = offsetSign;
		this.accrualFrequency = accrualFrequency;
		this.clearingWindow = clearingWindow;
		this.maxPdcPeriodMonth = maxPdcPeriodMonth;
		this.directCreditCode = directCreditCode;
		this.directCreditReversalCode = directCreditReversalCode;
		this.directDebitCode = directDebitCode;
		this.directDebitReversalCode = directDebitReversalCode;
		this.rcmsBusinessDate = rcmsBusinessDate;
		this.useDestinationHolidays = useDestinationHolidays;
		this.useSourceHolidays = useSourceHolidays;
		this.daylightSavingCode = daylightSavingCode;
		this.cutoffTime = cutoffTime;
		this.authorisedBy = authorisedBy;
		this.authorisedDate = authorisedDate;
		this.firstAuthorisedBy = firstAuthorisedBy;
		this.firstAuthorisedDate = firstAuthorisedDate;
		this.validNtnLtyFlag = validNtnLtyFlag;
		this.validResFlag = validResFlag;
		this.notaryFlag = notaryFlag;
		this.postalFlag = postalFlag;
		this.nonCoopFlag = nonCoopFlag;
		this.ctryExstngFlag = ctryExstngFlag;
		this.continentCode = continentCode;
		this.regionCode = regionCode;
		this.altCtryCodeNum = altCtryCodeNum;
		this.continent = continent;
		this.countryNameL01 = countryNameL01;
		this.countryNameL02 = countryNameL02;
		this.countryNameL03 = countryNameL03;
		this.countryNameL04 = countryNameL04;
		this.countryNameL05 = countryNameL05;
		this.region = region;
		this.isEu = isEu;
		this.createdByUserId = createdByUserId;
		this.verifiedByUserId = verifiedByUserId;
		this.modifiedByUserId = modifiedByUserId;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.countryCutoffFlag = countryCutoffFlag;
	}

	@Id

	@Column(name = "COUNTRY_CODE_EN", nullable = false, length = 2)
	public String getCountryCodeEn() {
		return this.countryCodeEn;
	}

	public void setCountryCodeEn(String countryCodeEn) {
		this.countryCodeEn = countryCodeEn;
	}

	@Column(name = "COUNTRY_CODE_NUM", precision = 3, scale = 0)
	public Short getCountryCodeNum() {
		return this.countryCodeNum;
	}

	public void setCountryCodeNum(Short countryCodeNum) {
		this.countryCodeNum = countryCodeNum;
	}

	@Column(name = "COUNTRY_NAME", length = 50)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "CURR_CODE", length = 3)
	public String getCurrCode() {
		return this.currCode;
	}

	public void setCurrCode(String currCode) {
		this.currCode = currCode;
	}

	@Column(name = "TIME_OFFSET", length = 5)
	public String getTimeOffset() {
		return this.timeOffset;
	}

	public void setTimeOffset(String timeOffset) {
		this.timeOffset = timeOffset;
	}

	@Column(name = "EOD_TIME", length = 5)
	public String getEodTime() {
		return this.eodTime;
	}

	public void setEodTime(String eodTime) {
		this.eodTime = eodTime;
	}

	@Column(name = "BOD_TIME", length = 5)
	public String getBodTime() {
		return this.bodTime;
	}

	public void setBodTime(String bodTime) {
		this.bodTime = bodTime;
	}

	@Column(name = "INTRADAY_EXE_TIME", length = 5)
	public String getIntradayExeTime() {
		return this.intradayExeTime;
	}

	public void setIntradayExeTime(String intradayExeTime) {
		this.intradayExeTime = intradayExeTime;
	}

	@Column(name = "PROCESS_NAME", length = 18)
	public String getProcessName() {
		return this.processName;
	}

	public void setProcessName(String processName) {
		this.processName = processName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PROCESS_TIME1", length = 29)
	public Date getProcessTime1() {
		return this.processTime1;
	}

	public void setProcessTime1(Date processTime1) {
		this.processTime1 = processTime1;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PROCESS_TIME2", length = 29)
	public Date getProcessTime2() {
		return this.processTime2;
	}

	public void setProcessTime2(Date processTime2) {
		this.processTime2 = processTime2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PROCESS_TIME3", length = 29)
	public Date getProcessTime3() {
		return this.processTime3;
	}

	public void setProcessTime3(Date processTime3) {
		this.processTime3 = processTime3;
	}

	@Column(name = "CREATED_BY", length = 310)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATION_DATE", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "VERIFIED_BY", length = 310)
	public String getVerifiedBy() {
		return this.verifiedBy;
	}

	public void setVerifiedBy(String verifiedBy) {
		this.verifiedBy = verifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VERIFIED_DATE", length = 29)
	public Date getVerifiedDate() {
		return this.verifiedDate;
	}

	public void setVerifiedDate(Date verifiedDate) {
		this.verifiedDate = verifiedDate;
	}

	@Column(name = "DELETE_FLAG", length = 1)
	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Column(name = "VERSION_NO", precision = 4, scale = 0)
	public Short getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(Short versionNo) {
		this.versionNo = versionNo;
	}

	@Column(name = "OFFSET_SIGN", length = 1)
	public String getOffsetSign() {
		return this.offsetSign;
	}

	public void setOffsetSign(String offsetSign) {
		this.offsetSign = offsetSign;
	}

	@Column(name = "ACCRUAL_FREQUENCY", length = 1)
	public String getAccrualFrequency() {
		return this.accrualFrequency;
	}

	public void setAccrualFrequency(String accrualFrequency) {
		this.accrualFrequency = accrualFrequency;
	}

	@Column(name = "CLEARING_WINDOW", precision = 3, scale = 0)
	public Short getClearingWindow() {
		return this.clearingWindow;
	}

	public void setClearingWindow(Short clearingWindow) {
		this.clearingWindow = clearingWindow;
	}

	@Column(name = "MAX_PDC_PERIOD_MONTH", precision = 8, scale = 0)
	public Integer getMaxPdcPeriodMonth() {
		return this.maxPdcPeriodMonth;
	}

	public void setMaxPdcPeriodMonth(Integer maxPdcPeriodMonth) {
		this.maxPdcPeriodMonth = maxPdcPeriodMonth;
	}

	@Column(name = "DIRECT_CREDIT_CODE", precision = 5, scale = 0)
	public Integer getDirectCreditCode() {
		return this.directCreditCode;
	}

	public void setDirectCreditCode(Integer directCreditCode) {
		this.directCreditCode = directCreditCode;
	}

	@Column(name = "DIRECT_CREDIT_REVERSAL_CODE", precision = 5, scale = 0)
	public Integer getDirectCreditReversalCode() {
		return this.directCreditReversalCode;
	}

	public void setDirectCreditReversalCode(Integer directCreditReversalCode) {
		this.directCreditReversalCode = directCreditReversalCode;
	}

	@Column(name = "DIRECT_DEBIT_CODE", precision = 5, scale = 0)
	public Integer getDirectDebitCode() {
		return this.directDebitCode;
	}

	public void setDirectDebitCode(Integer directDebitCode) {
		this.directDebitCode = directDebitCode;
	}

	@Column(name = "DIRECT_DEBIT_REVERSAL_CODE", precision = 5, scale = 0)
	public Integer getDirectDebitReversalCode() {
		return this.directDebitReversalCode;
	}

	public void setDirectDebitReversalCode(Integer directDebitReversalCode) {
		this.directDebitReversalCode = directDebitReversalCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RCMS_BUSINESS_DATE", length = 13)
	public Date getRcmsBusinessDate() {
		return this.rcmsBusinessDate;
	}

	public void setRcmsBusinessDate(Date rcmsBusinessDate) {
		this.rcmsBusinessDate = rcmsBusinessDate;
	}

	@Column(name = "USE_DESTINATION_HOLIDAYS", length = 1)
	public String getUseDestinationHolidays() {
		return this.useDestinationHolidays;
	}

	public void setUseDestinationHolidays(String useDestinationHolidays) {
		this.useDestinationHolidays = useDestinationHolidays;
	}

	@Column(name = "USE_SOURCE_HOLIDAYS", length = 1)
	public String getUseSourceHolidays() {
		return this.useSourceHolidays;
	}

	public void setUseSourceHolidays(String useSourceHolidays) {
		this.useSourceHolidays = useSourceHolidays;
	}

	@Column(name = "DAYLIGHT_SAVING_CODE", length = 8)
	public String getDaylightSavingCode() {
		return this.daylightSavingCode;
	}

	public void setDaylightSavingCode(String daylightSavingCode) {
		this.daylightSavingCode = daylightSavingCode;
	}

	@Column(name = "CUTOFF_TIME", precision = 6, scale = 0)
	public Integer getCutoffTime() {
		return this.cutoffTime;
	}

	public void setCutoffTime(Integer cutoffTime) {
		this.cutoffTime = cutoffTime;
	}

	@Column(name = "AUTHORISED_BY", length = 310)
	public String getAuthorisedBy() {
		return this.authorisedBy;
	}

	public void setAuthorisedBy(String authorisedBy) {
		this.authorisedBy = authorisedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUTHORISED_DATE", length = 29)
	public Date getAuthorisedDate() {
		return this.authorisedDate;
	}

	public void setAuthorisedDate(Date authorisedDate) {
		this.authorisedDate = authorisedDate;
	}

	@Column(name = "FIRST_AUTHORISED_BY", length = 310)
	public String getFirstAuthorisedBy() {
		return this.firstAuthorisedBy;
	}

	public void setFirstAuthorisedBy(String firstAuthorisedBy) {
		this.firstAuthorisedBy = firstAuthorisedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FIRST_AUTHORISED_DATE", length = 29)
	public Date getFirstAuthorisedDate() {
		return this.firstAuthorisedDate;
	}

	public void setFirstAuthorisedDate(Date firstAuthorisedDate) {
		this.firstAuthorisedDate = firstAuthorisedDate;
	}

	@Column(name = "VALID_NTN_LTY_FLAG", precision = 1, scale = 0)
	public Boolean getValidNtnLtyFlag() {
		return this.validNtnLtyFlag;
	}

	public void setValidNtnLtyFlag(Boolean validNtnLtyFlag) {
		this.validNtnLtyFlag = validNtnLtyFlag;
	}

	@Column(name = "VALID_RES_FLAG", precision = 1, scale = 0)
	public Boolean getValidResFlag() {
		return this.validResFlag;
	}

	public void setValidResFlag(Boolean validResFlag) {
		this.validResFlag = validResFlag;
	}

	@Column(name = "NOTARY_FLAG", precision = 1, scale = 0)
	public Boolean getNotaryFlag() {
		return this.notaryFlag;
	}

	public void setNotaryFlag(Boolean notaryFlag) {
		this.notaryFlag = notaryFlag;
	}

	@Column(name = "POSTAL_FLAG", precision = 1, scale = 0)
	public Boolean getPostalFlag() {
		return this.postalFlag;
	}

	public void setPostalFlag(Boolean postalFlag) {
		this.postalFlag = postalFlag;
	}

	@Column(name = "NON_COOP_FLAG", precision = 1, scale = 0)
	public Boolean getNonCoopFlag() {
		return this.nonCoopFlag;
	}

	public void setNonCoopFlag(Boolean nonCoopFlag) {
		this.nonCoopFlag = nonCoopFlag;
	}

	@Column(name = "CTRY_EXSTNG_FLAG", precision = 1, scale = 0)
	public Boolean getCtryExstngFlag() {
		return this.ctryExstngFlag;
	}

	public void setCtryExstngFlag(Boolean ctryExstngFlag) {
		this.ctryExstngFlag = ctryExstngFlag;
	}

	@Column(name = "CONTINENT_CODE", precision = 12, scale = 0)
	public Long getContinentCode() {
		return this.continentCode;
	}

	public void setContinentCode(Long continentCode) {
		this.continentCode = continentCode;
	}

	@Column(name = "REGION_CODE", precision = 12, scale = 0)
	public Long getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(Long regionCode) {
		this.regionCode = regionCode;
	}

	@Column(name = "ALT_CTRY_CODE_NUM", precision = 3, scale = 0)
	public Short getAltCtryCodeNum() {
		return this.altCtryCodeNum;
	}

	public void setAltCtryCodeNum(Short altCtryCodeNum) {
		this.altCtryCodeNum = altCtryCodeNum;
	}

	@Column(name = "CONTINENT", precision = 2, scale = 0)
	public Byte getContinent() {
		return this.continent;
	}

	public void setContinent(Byte continent) {
		this.continent = continent;
	}

	@Column(name = "COUNTRY_NAME_L01", length = 50)
	public String getCountryNameL01() {
		return this.countryNameL01;
	}

	public void setCountryNameL01(String countryNameL01) {
		this.countryNameL01 = countryNameL01;
	}

	@Column(name = "COUNTRY_NAME_L02", length = 50)
	public String getCountryNameL02() {
		return this.countryNameL02;
	}

	public void setCountryNameL02(String countryNameL02) {
		this.countryNameL02 = countryNameL02;
	}

	@Column(name = "COUNTRY_NAME_L03", length = 50)
	public String getCountryNameL03() {
		return this.countryNameL03;
	}

	public void setCountryNameL03(String countryNameL03) {
		this.countryNameL03 = countryNameL03;
	}

	@Column(name = "COUNTRY_NAME_L04", length = 50)
	public String getCountryNameL04() {
		return this.countryNameL04;
	}

	public void setCountryNameL04(String countryNameL04) {
		this.countryNameL04 = countryNameL04;
	}

	@Column(name = "COUNTRY_NAME_L05", length = 50)
	public String getCountryNameL05() {
		return this.countryNameL05;
	}

	public void setCountryNameL05(String countryNameL05) {
		this.countryNameL05 = countryNameL05;
	}

	@Column(name = "REGION", precision = 3, scale = 0)
	public Short getRegion() {
		return this.region;
	}

	public void setRegion(Short region) {
		this.region = region;
	}

	@Column(name = "IS_EU", length = 1)
	public String getIsEu() {
		return this.isEu;
	}

	public void setIsEu(String isEu) {
		this.isEu = isEu;
	}

	@Column(name = "CREATED_BY_USER_ID", scale = 0)
	public BigDecimal getCreatedByUserId() {
		return this.createdByUserId;
	}

	public void setCreatedByUserId(BigDecimal createdByUserId) {
		this.createdByUserId = createdByUserId;
	}

	@Column(name = "VERIFIED_BY_USER_ID", scale = 0)
	public BigDecimal getVerifiedByUserId() {
		return this.verifiedByUserId;
	}

	public void setVerifiedByUserId(BigDecimal verifiedByUserId) {
		this.verifiedByUserId = verifiedByUserId;
	}

	@Column(name = "MODIFIED_BY_USER_ID", scale = 0)
	public BigDecimal getModifiedByUserId() {
		return this.modifiedByUserId;
	}

	public void setModifiedByUserId(BigDecimal modifiedByUserId) {
		this.modifiedByUserId = modifiedByUserId;
	}

	@Column(name = "MODIFIED_BY", length = 310)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DATE", length = 29)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "COUNTRY_CUTOFF_FLAG", length = 1)
	public String getCountryCutoffFlag() {
		return this.countryCutoffFlag;
	}

	public void setCountryCutoffFlag(String countryCutoffFlag) {
		this.countryCutoffFlag = countryCutoffFlag;
	}

}
