package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BccStateRef generated by hbm2java
 */
@Entity
@Table(name = "bcc_state_ref", schema = "public")
public class BccStateRef implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2997988859409450293L;
	private BccStateRefId id;
	private String countryCodeNum;
	private String stateName;
	private String stateZone;
	private String timezoneCode;
	private Character clearingLocationFlag;
	private BigDecimal createdByUserId;
	private String createdBy;
	private Date creationDate;
	private BigDecimal modifiedByUserId;
	private String modifiedBy;
	private Date modifiedDate;
	private BigDecimal verifiedByUserId;
	private String verifiedBy;
	private Date verifiedDate;
	private BigDecimal approvedByUserId;
	private String approvedBy;
	private Date approvalDate;
	private String rejectionReasonCode;
	private String rejectionReasonValue;
	private String rejectionReason;
	private Short versionNo;

	public BccStateRef() {
	}

	public BccStateRef(BccStateRefId id) {
		this.id = id;
	}

	public BccStateRef(BccStateRefId id, String countryCodeNum, String stateName, String stateZone, String timezoneCode,
			Character clearingLocationFlag, BigDecimal createdByUserId, String createdBy, Date creationDate,
			BigDecimal modifiedByUserId, String modifiedBy, Date modifiedDate, BigDecimal verifiedByUserId,
			String verifiedBy, Date verifiedDate, BigDecimal approvedByUserId, String approvedBy, Date approvalDate,
			String rejectionReasonCode, String rejectionReasonValue, String rejectionReason, Short versionNo) {
		this.id = id;
		this.countryCodeNum = countryCodeNum;
		this.stateName = stateName;
		this.stateZone = stateZone;
		this.timezoneCode = timezoneCode;
		this.clearingLocationFlag = clearingLocationFlag;
		this.createdByUserId = createdByUserId;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.modifiedByUserId = modifiedByUserId;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.verifiedByUserId = verifiedByUserId;
		this.verifiedBy = verifiedBy;
		this.verifiedDate = verifiedDate;
		this.approvedByUserId = approvedByUserId;
		this.approvedBy = approvedBy;
		this.approvalDate = approvalDate;
		this.rejectionReasonCode = rejectionReasonCode;
		this.rejectionReasonValue = rejectionReasonValue;
		this.rejectionReason = rejectionReason;
		this.versionNo = versionNo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "stateCode", column = @Column(name = "state_code", nullable = false, length = 10)),
			@AttributeOverride(name = "countryCodeEn", column = @Column(name = "country_code_en", nullable = false, length = 2)) })
	public BccStateRefId getId() {
		return this.id;
	}

	public void setId(BccStateRefId id) {
		this.id = id;
	}

	@Column(name = "country_code_num", length = 3)
	public String getCountryCodeNum() {
		return this.countryCodeNum;
	}

	public void setCountryCodeNum(String countryCodeNum) {
		this.countryCodeNum = countryCodeNum;
	}

	@Column(name = "state_name", length = 100)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@Column(name = "state_zone", length = 100)
	public String getStateZone() {
		return this.stateZone;
	}

	public void setStateZone(String stateZone) {
		this.stateZone = stateZone;
	}

	@Column(name = "timezone_code", length = 3)
	public String getTimezoneCode() {
		return this.timezoneCode;
	}

	public void setTimezoneCode(String timezoneCode) {
		this.timezoneCode = timezoneCode;
	}

	@Column(name = "clearing_location_flag", length = 1)
	public Character getClearingLocationFlag() {
		return this.clearingLocationFlag;
	}

	public void setClearingLocationFlag(Character clearingLocationFlag) {
		this.clearingLocationFlag = clearingLocationFlag;
	}

	@Column(name = "created_by_user_id", scale = 0)
	public BigDecimal getCreatedByUserId() {
		return this.createdByUserId;
	}

	public void setCreatedByUserId(BigDecimal createdByUserId) {
		this.createdByUserId = createdByUserId;
	}

	@Column(name = "created_by", length = 310)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "modified_by_user_id", scale = 0)
	public BigDecimal getModifiedByUserId() {
		return this.modifiedByUserId;
	}

	public void setModifiedByUserId(BigDecimal modifiedByUserId) {
		this.modifiedByUserId = modifiedByUserId;
	}

	@Column(name = "modified_by", length = 310)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 29)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "verified_by_user_id", scale = 0)
	public BigDecimal getVerifiedByUserId() {
		return this.verifiedByUserId;
	}

	public void setVerifiedByUserId(BigDecimal verifiedByUserId) {
		this.verifiedByUserId = verifiedByUserId;
	}

	@Column(name = "verified_by", length = 310)
	public String getVerifiedBy() {
		return this.verifiedBy;
	}

	public void setVerifiedBy(String verifiedBy) {
		this.verifiedBy = verifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "verified_date", length = 29)
	public Date getVerifiedDate() {
		return this.verifiedDate;
	}

	public void setVerifiedDate(Date verifiedDate) {
		this.verifiedDate = verifiedDate;
	}

	@Column(name = "approved_by_user_id", scale = 0)
	public BigDecimal getApprovedByUserId() {
		return this.approvedByUserId;
	}

	public void setApprovedByUserId(BigDecimal approvedByUserId) {
		this.approvedByUserId = approvedByUserId;
	}

	@Column(name = "approved_by", length = 310)
	public String getApprovedBy() {
		return this.approvedBy;
	}

	public void setApprovedBy(String approvedBy) {
		this.approvedBy = approvedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approval_date", length = 29)
	public Date getApprovalDate() {
		return this.approvalDate;
	}

	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}

	@Column(name = "rejection_reason_code", length = 3)
	public String getRejectionReasonCode() {
		return this.rejectionReasonCode;
	}

	public void setRejectionReasonCode(String rejectionReasonCode) {
		this.rejectionReasonCode = rejectionReasonCode;
	}

	@Column(name = "rejection_reason_value", length = 3)
	public String getRejectionReasonValue() {
		return this.rejectionReasonValue;
	}

	public void setRejectionReasonValue(String rejectionReasonValue) {
		this.rejectionReasonValue = rejectionReasonValue;
	}

	@Column(name = "rejection_reason", length = 100)
	public String getRejectionReason() {
		return this.rejectionReason;
	}

	public void setRejectionReason(String rejectionReason) {
		this.rejectionReason = rejectionReason;
	}

	@Column(name = "version_no", precision = 3, scale = 0)
	public Short getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(Short versionNo) {
		this.versionNo = versionNo;
	}

}
