package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChAddressInfo generated by hbm2java
 */
@Entity
@Table(name = "ch_address_info", schema = "public")
public class ChAddressInfo implements java.io.Serializable {

	private BigDecimal addressId;
	private BigDecimal addressShortCode;
	private String addressLine1;
	private String addressLine2;
	private String addressLine3;
	private String addressLine4;
	private String city;
	private BigDecimal postalCode;
	private String state;
	private String country;
	private Date validTo;
	private Date validFrom;

	public ChAddressInfo() {
	}

	public ChAddressInfo(BigDecimal addressId) {
		this.addressId = addressId;
	}

	public ChAddressInfo(BigDecimal addressId, BigDecimal addressShortCode, String addressLine1, String addressLine2,
			String addressLine3, String addressLine4, String city, BigDecimal postalCode, String state, String country,
			Date validTo, Date validFrom) {
		this.addressId = addressId;
		this.addressShortCode = addressShortCode;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.addressLine3 = addressLine3;
		this.addressLine4 = addressLine4;
		this.city = city;
		this.postalCode = postalCode;
		this.state = state;
		this.country = country;
		this.validTo = validTo;
		this.validFrom = validFrom;
	}

	@Id

	@Column(name = "ADDRESS_ID", nullable = false, scale = 0)
	public BigDecimal getAddressId() {
		return this.addressId;
	}

	public void setAddressId(BigDecimal addressId) {
		this.addressId = addressId;
	}

	@Column(name = "ADDRESS_SHORT_CODE", scale = 0)
	public BigDecimal getAddressShortCode() {
		return this.addressShortCode;
	}

	public void setAddressShortCode(BigDecimal addressShortCode) {
		this.addressShortCode = addressShortCode;
	}

	@Column(name = "ADDRESS_LINE1")
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE2")
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "ADDRESS_LINE3")
	public String getAddressLine3() {
		return this.addressLine3;
	}

	public void setAddressLine3(String addressLine3) {
		this.addressLine3 = addressLine3;
	}

	@Column(name = "ADDRESS_LINE4")
	public String getAddressLine4() {
		return this.addressLine4;
	}

	public void setAddressLine4(String addressLine4) {
		this.addressLine4 = addressLine4;
	}

	@Column(name = "CITY", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "POSTAL_CODE", precision = 131089, scale = 0)
	public BigDecimal getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(BigDecimal postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "STATE", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTRY", length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VALID_TO", length = 13)
	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VALID_FROM", length = 13)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

}
