package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChChannelCustGrpMapping generated by hbm2java
 */
@Entity
@Table(name = "ch_channel_cust_grp_mapping", schema = "public")
public class ChChannelCustGrpMapping implements java.io.Serializable {

	private ChChannelCustGrpMappingId id;
	private ChChannelCustomer chChannelCustomer;
	private ChGroup chGroup;

	public ChChannelCustGrpMapping() {
	}

	public ChChannelCustGrpMapping(ChChannelCustGrpMappingId id) {
		this.id = id;
	}

	public ChChannelCustGrpMapping(ChChannelCustGrpMappingId id, ChChannelCustomer chChannelCustomer, ChGroup chGroup) {
		this.id = id;
		this.chChannelCustomer = chChannelCustomer;
		this.chGroup = chGroup;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "groupId", column = @Column(name = "group_id", scale = 0)),
			@AttributeOverride(name = "channelCustId", column = @Column(name = "channel_cust_id", scale = 0)) })
	public ChChannelCustGrpMappingId getId() {
		return this.id;
	}

	public void setId(ChChannelCustGrpMappingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER, targetEntity=com.dcsoft.capmkt.orm.ChChannelCustomer.class)
	@JoinColumn(name = "channel_cust_id", insertable = false, updatable = false)
	public ChChannelCustomer getChChannelCustomer() {
		return this.chChannelCustomer;
	}

	public void setChChannelCustomer(ChChannelCustomer chChannelCustomer) {
		this.chChannelCustomer = chChannelCustomer;
	}

	@ManyToOne(fetch = FetchType.EAGER, targetEntity=com.dcsoft.capmkt.orm.ChGroup.class)
	@JoinColumn(name = "group_id", insertable = false, updatable = false)
	public ChGroup getChGroup() {
		return this.chGroup;
	}

	public void setChGroup(ChGroup chGroup) {
		this.chGroup = chGroup;
	}

}
