package com.dcsoft.capmkt.orm;
// Generated May 22, 2016 10:33:07 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChDapCustMapping generated by hbm2java
 */
@Entity
@Table(name = "ch_dap_cust_mapping", schema = "public")
public class ChDapCustMapping implements java.io.Serializable {

	private static final long serialVersionUID = -4835057529752900132L;
	private ChDapCustMappingId id;
	private ChDap chDap;
	private ChChannelCustomer chChannelCustomer;

	public ChDapCustMapping() {
	}

	public ChDapCustMapping(ChDapCustMappingId id, ChDap chDap, ChChannelCustomer chChannelCustomer) {
		this.id = id;
		this.chDap = chDap;
		this.chChannelCustomer = chChannelCustomer;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dapId", column = @Column(name = "dap_id", nullable = false, scale = 0)),
			@AttributeOverride(name = "channelCustId", column = @Column(name = "channel_cust_id", nullable = false, scale = 0)) })
	public ChDapCustMappingId getId() {
		return this.id;
	}

	public void setId(ChDapCustMappingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dap_id", nullable = false, insertable = false, updatable = false)
	public ChDap getChDap() {
		return this.chDap;
	}

	public void setChDap(ChDap chDap) {
		this.chDap = chDap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "channel_cust_id", nullable = false, insertable = false, updatable = false)
	public ChChannelCustomer getChChannelCustomer() {
		return this.chChannelCustomer;
	}

	public void setChChannelCustomer(ChChannelCustomer chChannelCustomer) {
		this.chChannelCustomer = chChannelCustomer;
	}

}
