package com.dcsoft.capmkt.orm;
// Generated May 22, 2016 10:33:07 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChDapCustMappingId generated by hbm2java
 */
@Embeddable
public class ChDapCustMappingId implements java.io.Serializable {

	private static final long serialVersionUID = 7302353081602039475L;
	private BigDecimal dapId;
	private BigDecimal channelCustId;

	public ChDapCustMappingId() {
	}

	public ChDapCustMappingId(BigDecimal dapId, BigDecimal channelCustId) {
		this.dapId = dapId;
		this.channelCustId = channelCustId;
	}

	@Column(name = "dap_id", nullable = false, scale = 0)
	public BigDecimal getDapId() {
		return this.dapId;
	}

	public void setDapId(BigDecimal dapId) {
		this.dapId = dapId;
	}

	@Column(name = "channel_cust_id", nullable = false, scale = 0)
	public BigDecimal getChannelCustId() {
		return this.channelCustId;
	}

	public void setChannelCustId(BigDecimal channelCustId) {
		this.channelCustId = channelCustId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChDapCustMappingId))
			return false;
		ChDapCustMappingId castOther = (ChDapCustMappingId) other;

		return ((this.getDapId() == castOther.getDapId()) || (this.getDapId() != null && castOther.getDapId() != null
				&& this.getDapId().equals(castOther.getDapId())))
				&& ((this.getChannelCustId() == castOther.getChannelCustId())
						|| (this.getChannelCustId() != null && castOther.getChannelCustId() != null
								&& this.getChannelCustId().equals(castOther.getChannelCustId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDapId() == null ? 0 : this.getDapId().hashCode());
		result = 37 * result + (getChannelCustId() == null ? 0 : this.getChannelCustId().hashCode());
		return result;
	}

}
