package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChDapUserMappingId generated by hbm2java
 */
@Embeddable
public class ChDapUserMappingId implements java.io.Serializable {

	private String userid;
	private BigDecimal dapId;

	public ChDapUserMappingId() {
	}

	public ChDapUserMappingId(String userid, BigDecimal dapId) {
		this.userid = userid;
		this.dapId = dapId;
	}

	@Column(name = "userid", length = 20)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "dap_id", scale = 0)
	public BigDecimal getDapId() {
		return this.dapId;
	}

	public void setDapId(BigDecimal dapId) {
		this.dapId = dapId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChDapUserMappingId))
			return false;
		ChDapUserMappingId castOther = (ChDapUserMappingId) other;

		return ((this.getUserid() == castOther.getUserid()) || (this.getUserid() != null
				&& castOther.getUserid() != null && this.getUserid().equals(castOther.getUserid())))
				&& ((this.getDapId() == castOther.getDapId()) || (this.getDapId() != null
						&& castOther.getDapId() != null && this.getDapId().equals(castOther.getDapId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserid() == null ? 0 : this.getUserid().hashCode());
		result = 37 * result + (getDapId() == null ? 0 : this.getDapId().hashCode());
		return result;
	}

}
