package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChDapUserMapping generated by hbm2java
 */
@Entity
@Table(name = "ch_dap_user_mapping", schema = "public")
public class ChDapUserMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5561792327775596000L;
	private ChDapUserMappingId id;
	private ChDap chDap;
	private ChUser chUser;

	public ChDapUserMapping() {
	}

	public ChDapUserMapping(ChDapUserMappingId id) {
		this.id = id;
	}

	public ChDapUserMapping(ChDapUserMappingId id, ChDap chDap, ChUser chUser) {
		this.id = id;
		this.chDap = chDap;
		this.chUser = chUser;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userid", column = @Column(name = "userid", length = 20)),
			@AttributeOverride(name = "dapId", column = @Column(name = "dap_id", scale = 0)) })
	public ChDapUserMappingId getId() {
		return this.id;
	}

	public void setId(ChDapUserMappingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER,targetEntity=com.dcsoft.capmkt.orm.ChDap.class)
	@JoinColumn(name = "dap_id", insertable = false, updatable = false)
	public ChDap getChDap() {
		return this.chDap;
	}

	public void setChDap(ChDap chDap) {
		this.chDap = chDap;
	}

	@ManyToOne(fetch = FetchType.EAGER , targetEntity=com.dcsoft.capmkt.orm.ChUser.class)
	@JoinColumn(name = "userid", insertable = false, updatable = false)
	public ChUser getChUser() {
		return this.chUser;
	}

	public void setChUser(ChUser chUser) {
		this.chUser = chUser;
	}

}
