package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChDap generated by hbm2java
 */
@Entity
@Table(name = "ch_dap", schema = "public")
public class ChDap implements java.io.Serializable {

	private BigDecimal dapId;
	private String dapName;
	private String dapDescription;
	private BigDecimal dapServiceId;
	private BigDecimal channelCustId;
	private Set chDapUserMappings = new HashSet(0);

	public ChDap() {
	}

	public ChDap(BigDecimal dapId, BigDecimal channelCustId) {
		this.dapId = dapId;
		this.channelCustId = channelCustId;
	}

	public ChDap(BigDecimal dapId, String dapName, String dapDescription, BigDecimal dapServiceId,
			BigDecimal channelCustId, Set chDapUserMappings) {
		this.dapId = dapId;
		this.dapName = dapName;
		this.dapDescription = dapDescription;
		this.dapServiceId = dapServiceId;
		this.channelCustId = channelCustId;
		this.chDapUserMappings = chDapUserMappings;
	}

	@Id

	@Column(name = "dap_id", nullable = false, scale = 0)
	public BigDecimal getDapId() {
		return this.dapId;
	}

	public void setDapId(BigDecimal dapId) {
		this.dapId = dapId;
	}

	@Column(name = "dap_name", length = 100)
	public String getDapName() {
		return this.dapName;
	}

	public void setDapName(String dapName) {
		this.dapName = dapName;
	}

	@Column(name = "dap_description", length = 200)
	public String getDapDescription() {
		return this.dapDescription;
	}

	public void setDapDescription(String dapDescription) {
		this.dapDescription = dapDescription;
	}

	@Column(name = "dap_service_id", scale = 0)
	public BigDecimal getDapServiceId() {
		return this.dapServiceId;
	}

	public void setDapServiceId(BigDecimal dapServiceId) {
		this.dapServiceId = dapServiceId;
	}

	@Column(name = "channel_cust_id", nullable = false, scale = 0)
	public BigDecimal getChannelCustId() {
		return this.channelCustId;
	}

	public void setChannelCustId(BigDecimal channelCustId) {
		this.channelCustId = channelCustId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chDap", targetEntity=com.dcsoft.capmkt.orm.ChDapUserMapping.class)
	public Set getChDapUserMappings() {
		return this.chDapUserMappings;
	}

	public void setChDapUserMappings(Set chDapUserMappings) {
		this.chDapUserMappings = chDapUserMappings;
	}

}
