package com.dcsoft.capmkt.orm;
// Generated May 22, 2016 10:33:07 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChDapValues generated by hbm2java
 */
@Entity
@Table(name = "ch_dap_values", schema = "public")
public class ChDapValues implements java.io.Serializable {

	private static final long serialVersionUID = 958452818023449080L;
	private ChDapValuesId id;
	private ChDap chDap;

	public ChDapValues() {
	}

	public ChDapValues(ChDapValuesId id) {
		this.id = id;
	}

	public ChDapValues(ChDapValuesId id, ChDap chDap) {
		this.id = id;
		this.chDap = chDap;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "dapId", column = @Column(name = "dap_id")),
			@AttributeOverride(name = "dapValue", column = @Column(name = "dap_value")) })
	public ChDapValuesId getId() {
		return this.id;
	}

	public void setId(ChDapValuesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dap_id", insertable = false, updatable = false)
	public ChDap getChDap() {
		return this.chDap;
	}

	public void setChDap(ChDap chDap) {
		this.chDap = chDap;
	}

}
