package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChFapUserMapping generated by hbm2java
 */
@Entity
@Table(name = "ch_fap_user_mapping", schema = "public")
public class ChFapUserMapping implements java.io.Serializable {

	private ChFapUserMappingId id;
	private ChFap chFap;
	private ChUser chUser;

	public ChFapUserMapping() {
	}

	public ChFapUserMapping(ChFapUserMappingId id) {
		this.id = id;
	}

	public ChFapUserMapping(ChFapUserMappingId id, ChFap chFap, ChUser chUser) {
		this.id = id;
		this.chFap = chFap;
		this.chUser = chUser;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userid", column = @Column(name = "userid", length = 20)),
			@AttributeOverride(name = "fapId", column = @Column(name = "fap_id", scale = 0)) })
	public ChFapUserMappingId getId() {
		return this.id;
	}

	public void setId(ChFapUserMappingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fap_id", insertable = false, updatable = false)
	public ChFap getChFap() {
		return this.chFap;
	}

	public void setChFap(ChFap chFap) {
		this.chFap = chFap;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userid", insertable = false, updatable = false)
	public ChUser getChUser() {
		return this.chUser;
	}

	public void setChUser(ChUser chUser) {
		this.chUser = chUser;
	}

}
