package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChFap generated by hbm2java
 */
@Entity
@Table(name = "ch_fap", schema = "public")
public class ChFap implements java.io.Serializable {

	private BigDecimal fapId;
	private String fapName;
	private String fapDescription;
	private byte channel;
	private BigDecimal createdBy;
	private Date createdDate;
	private Set chFapUserMappings = new HashSet(0);

	public ChFap() {
	}

	public ChFap(BigDecimal fapId, byte channel) {
		this.fapId = fapId;
		this.channel = channel;
	}

	public ChFap(BigDecimal fapId, String fapName, String fapDescription, byte channel, BigDecimal createdBy,
			Date createdDate, Set chFapUserMappings) {
		this.fapId = fapId;
		this.fapName = fapName;
		this.fapDescription = fapDescription;
		this.channel = channel;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.chFapUserMappings = chFapUserMappings;
	}

	@Id

	@Column(name = "fap_id", nullable = false, scale = 0)
	public BigDecimal getFapId() {
		return this.fapId;
	}

	public void setFapId(BigDecimal fapId) {
		this.fapId = fapId;
	}

	@Column(name = "fap_name", length = 100)
	public String getFapName() {
		return this.fapName;
	}

	public void setFapName(String fapName) {
		this.fapName = fapName;
	}

	@Column(name = "fap_description", length = 200)
	public String getFapDescription() {
		return this.fapDescription;
	}

	public void setFapDescription(String fapDescription) {
		this.fapDescription = fapDescription;
	}

	@Column(name = "channel", nullable = false, precision = 2, scale = 0)
	public byte getChannel() {
		return this.channel;
	}

	public void setChannel(byte channel) {
		this.channel = channel;
	}

	@Column(name = "created_by", scale = 0)
	public BigDecimal getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(BigDecimal createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 13)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chFap" , targetEntity=com.dcsoft.capmkt.orm.ChFapUserMapping.class)
	public Set getChFapUserMappings() {
		return this.chFapUserMappings;
	}

	public void setChFapUserMappings(Set chFapUserMappings) {
		this.chFapUserMappings = chFapUserMappings;
	}

}
