package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChFapServiceMappingId generated by hbm2java
 */
@Embeddable
public class ChFapServiceMappingId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8040931370122709763L;
	private BigDecimal serviceDetailId;
	private BigDecimal fapId;

	public ChFapServiceMappingId() {
	}

	public ChFapServiceMappingId(BigDecimal serviceDetailId, BigDecimal fapId) {
		this.serviceDetailId = serviceDetailId;
		this.fapId = fapId;
	}

	@Column(name = "service_detail_id", length = 20)
	public BigDecimal getServiceDetailId() {
		return serviceDetailId;
	}

	public void setServiceDetailId(BigDecimal serviceDetailId) {
		this.serviceDetailId = serviceDetailId;
	}

	@Column(name = "fap_id", scale = 0)
	public BigDecimal getFapId() {
		return this.fapId;
	}

	public void setFapId(BigDecimal fapId) {
		this.fapId = fapId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChFapServiceMappingId))
			return false;
		ChFapServiceMappingId castOther = (ChFapServiceMappingId) other;

		return ((this.getServiceDetailId() == castOther.getServiceDetailId()) || (this.getServiceDetailId() != null
				&& castOther.getServiceDetailId() != null && this.getServiceDetailId().equals(castOther.getServiceDetailId())))
				&& ((this.getFapId() == castOther.getFapId()) || (this.getFapId() != null
						&& castOther.getFapId() != null && this.getFapId().equals(castOther.getFapId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getServiceDetailId() == null ? 0 : this.getServiceDetailId().hashCode());
		result = 37 * result + (getFapId() == null ? 0 : this.getFapId().hashCode());
		return result;
	}

}
