package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChFapServiceMapping generated by hbm2java
 */
@Entity
@Table(name = "ch_fap_service_mapping", schema = "public")
public class ChFapServiceMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8611487426269467251L;
	private ChFapServiceMappingId id;
	private ChFap chFap;
	private ChServiceDetails chServiceDetails;

	public ChFapServiceMapping() {
	}

	public ChFapServiceMapping(ChFapServiceMappingId id) {
		this.id = id;
	}

	public ChFapServiceMapping(ChFapServiceMappingId id, ChFap chFap, ChServiceDetails chServiceDetails) {
		this.id = id;
		this.chFap = chFap;
		this.chServiceDetails = chServiceDetails;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "serviceDetailId", column = @Column(name = "service_detail_id", length = 20)),
			@AttributeOverride(name = "fapId", column = @Column(name = "fap_id", scale = 0)) })
	public ChFapServiceMappingId getId() {
		return this.id;
	}

	public void setId(ChFapServiceMappingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fap_id", insertable = false, updatable = false)
	public ChFap getChFap() {
		return this.chFap;
	}

	public void setChFap(ChFap chFap) {
		this.chFap = chFap;
	}

	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "service_detail_id", insertable = false, updatable = false)
	public ChServiceDetails getChServiceDetails() {
		return chServiceDetails;
	}

	public void setChServiceDetails(ChServiceDetails chServiceDetails) {
		this.chServiceDetails = chServiceDetails;
	}

}
