package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChGroup generated by hbm2java
 */
@Entity
@Table(name = "ch_group", schema = "public")
public class ChGroup implements java.io.Serializable {

	private BigDecimal groupId;
	private String groupName;
	private String groupdesc;
	private Set chChannelCustGrpMappings = new HashSet(0);
	private Set chUserGroupMappings = new HashSet(0);

	public ChGroup() {
	}

	public ChGroup(BigDecimal groupId, String groupName) {
		this.groupId = groupId;
		this.groupName = groupName;
	}

	public ChGroup(BigDecimal groupId, String groupName, String groupdesc, Set chChannelCustGrpMappings,
			Set chUserGroupMappings) {
		this.groupId = groupId;
		this.groupName = groupName;
		this.groupdesc = groupdesc;
		this.chChannelCustGrpMappings = chChannelCustGrpMappings;
		this.chUserGroupMappings = chUserGroupMappings;
	}

	@Id
	@GeneratedValue
	@Column(name = "group_id", unique = true, nullable = false, scale = 0)
	public BigDecimal getGroupId() {
		return this.groupId;
	}

	public void setGroupId(BigDecimal groupId) {
		this.groupId = groupId;
	}

	@Column(name = "group_name", nullable = false)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "groupdesc", length = 1024)
	public String getGroupdesc() {
		return this.groupdesc;
	}

	public void setGroupdesc(String groupdesc) {
		this.groupdesc = groupdesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chGroup", targetEntity= com.dcsoft.capmkt.orm.ChChannelCustGrpMapping.class)
	public Set getChChannelCustGrpMappings() {
		return this.chChannelCustGrpMappings;
	}

	public void setChChannelCustGrpMappings(Set chChannelCustGrpMappings) {
		this.chChannelCustGrpMappings = chChannelCustGrpMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chGroup",targetEntity= com.dcsoft.capmkt.orm.ChUserGroupMapping.class)
	public Set getChUserGroupMappings() {
		return this.chUserGroupMappings;
	}

	public void setChUserGroupMappings(Set chUserGroupMappings) {
		this.chUserGroupMappings = chUserGroupMappings;
	}

}
