package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChHost generated by hbm2java
 */
@Entity
@Table(name = "ch_host", schema = "public")
public class ChHost implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5498416472756876317L;
	private BigDecimal hostId;
	private String hostName;
	private String hostDescription;
	private String hostCountryCode;
	private Set chServiceDetailses = new HashSet(0);

	public ChHost() {
	}

	public ChHost(BigDecimal hostId) {
		this.hostId = hostId;
	}

	public ChHost(BigDecimal hostId, String hostName, String hostDescription, String hostCountryCode,
			Set chServiceDetailses) {
		this.hostId = hostId;
		this.hostName = hostName;
		this.hostDescription = hostDescription;
		this.hostCountryCode = hostCountryCode;
		this.chServiceDetailses = chServiceDetailses;
	}

	@Id
	@Column(name = "host_id", unique = true, nullable = false, scale = 0)
	public BigDecimal getHostId() {
		return this.hostId;
	}

	public void setHostId(BigDecimal hostId) {
		this.hostId = hostId;
	}

	@Column(name = "host_name", length = 100)
	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	@Column(name = "host_description", length = 200)
	public String getHostDescription() {
		return this.hostDescription;
	}

	public void setHostDescription(String hostDescription) {
		this.hostDescription = hostDescription;
	}

	@Column(name = "host_country_code", length = 2)
	public String getHostCountryCode() {
		return this.hostCountryCode;
	}

	public void setHostCountryCode(String hostCountryCode) {
		this.hostCountryCode = hostCountryCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chHost", targetEntity=com.dcsoft.capmkt.orm.ChServiceDetails.class)
	public Set getChServiceDetailses() {
		return this.chServiceDetailses;
	}

	public void setChServiceDetailses(Set chServiceDetailses) {
		this.chServiceDetailses = chServiceDetailses;
	}

}
