package com.dcsoft.capmkt.orm;
// Generated Jun 5, 2016 11:25:49 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChObjectMappingId generated by hbm2java
 */
@Embeddable
public class ChObjectMappingId implements java.io.Serializable {

	private static final long serialVersionUID = 6564309473120325955L;
	private String objectName;
	private String objectId;
	private String objectHash;

	public ChObjectMappingId() {
	}

	public ChObjectMappingId(String objectName, String objectId, String objectHash) {
		this.objectName = objectName;
		this.objectId = objectId;
		this.objectHash = objectHash;
	}

	@Column(name = "objectName", length = 100)
	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	@Column(name = "objectID")
	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	@Column(name = "objectHash")
	public String getObjectHash() {
		return this.objectHash;
	}

	public void setObjectHash(String objectHash) {
		this.objectHash = objectHash;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChObjectMappingId))
			return false;
		ChObjectMappingId castOther = (ChObjectMappingId) other;

		return ((this.getObjectName() == castOther.getObjectName()) || (this.getObjectName() != null
				&& castOther.getObjectName() != null && this.getObjectName().equals(castOther.getObjectName())))
				&& ((this.getObjectId() == castOther.getObjectId()) || (this.getObjectId() != null
						&& castOther.getObjectId() != null && this.getObjectId().equals(castOther.getObjectId())))
				&& ((this.getObjectHash() == castOther.getObjectHash())
						|| (this.getObjectHash() != null && castOther.getObjectHash() != null
								&& this.getObjectHash().equals(castOther.getObjectHash())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getObjectName() == null ? 0 : this.getObjectName().hashCode());
		result = 37 * result + (getObjectId() == null ? 0 : this.getObjectId().hashCode());
		result = 37 * result + (getObjectHash() == null ? 0 : this.getObjectHash().hashCode());
		return result;
	}

}
