package com.dcsoft.capmkt.orm;
// Generated Jun 5, 2016 11:25:49 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ChObjectMapping generated by hbm2java
 */
@Entity
@Table(name = "ch_object_mapping", schema = "public")
public class ChObjectMapping implements java.io.Serializable {

	private static final long serialVersionUID = -2976653392121460147L;
	private ChObjectMappingId id;

	public ChObjectMapping() {
	}

	public ChObjectMapping(ChObjectMappingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "objectName", column = @Column(name = "objectName", length = 100)),
			@AttributeOverride(name = "objectId", column = @Column(name = "objectID")),
			@AttributeOverride(name = "objectHash", column = @Column(name = "objectHash")) })
	public ChObjectMappingId getId() {
		return this.id;
	}

	public void setId(ChObjectMappingId id) {
		this.id = id;
	}

}
