package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChUserGroupMapping generated by hbm2java
 */
@Entity
@Table(name = "ch_user_group_mapping", schema = "public")
public class ChUserGroupMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7546245081865423260L;
	private ChUserGroupMappingId id;
	private ChGroup chGroup;
	private ChUser chUser;

	public ChUserGroupMapping() {
	}

	public ChUserGroupMapping(ChUserGroupMappingId id) {
		this.id = id;
	}

	public ChUserGroupMapping(ChUserGroupMappingId id, ChGroup chGroup, ChUser chUser) {
		this.id = id;
		this.chGroup = chGroup;
		this.chUser = chUser;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "groupid", column = @Column(name = "groupid", scale = 0)),
			@AttributeOverride(name = "userid", column = @Column(name = "userid", length = 20)) })
	public ChUserGroupMappingId getId() {
		return this.id;
	}

	public void setId(ChUserGroupMappingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "groupid", insertable = false, updatable = false)
	public ChGroup getChGroup() {
		return this.chGroup;
	}

	public void setChGroup(ChGroup chGroup) {
		this.chGroup = chGroup;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userid", insertable = false, updatable = false)
	public ChUser getChUser() {
		return this.chUser;
	}

	public void setChUser(ChUser chUser) {
		this.chUser = chUser;
	}

}
