package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CrwCaRspnsId generated by hbm2java
 */
@Embeddable
public class CrwCaRspnsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6081680335699807075L;
	private String crwCaId;
	private String crwClientRef;
	private String crwNcsRefNum;
	private String crwSecId;
	private String crwScaId;
	private Integer crwOptnSeq;
	private String crwOptnDesc;
	private BigDecimal crwEligibleQty;
	private BigDecimal crwAdvsdQty;
	private Integer crwSiInd;
	private Date crwEntryDt;
	private String crwRmrks;
	private String crwSta;
	private Integer crwStaCd;
	private Integer crwPrevSta;
	private String crwStaDesc;
	private BigDecimal crwPndingAproval;
	private BigDecimal crwOvrSubsQty;
	private String crwTndrPricTyp;
	private Integer crwPriceTypCd;
	private BigDecimal crwTndrPrice;
	private Date modificationDate;
	private Short crwCaRspnsVer;
	private String crwSecName;
	private String branchid;
	private String userid;
	private String crwRjctnRsn;
	private String crwFiller1;
	private String crwFiller5;
	private String crwFiller6;
	private BigDecimal crwFiller7;
	private BigDecimal crwFiller8;
	private String crwFiller9;
	private String modifiedby;
	private String crwUpldfilename;
	private Short versionnum;
	private String crwAuthby;
	private String crwUniqueCorpRef;
	private String crwBpId;
	private String crwBpName;
	private String cancClntRefer;
	private String crwBansrefnum;
	private String crwFunctionofmsg;
	private String crwEvntTyp;
	private String bancsinternalid;
	private String crwExtRmrks;
	private String crwPosBucket;
	private BigDecimal crwConditionalQty;
	private Date crwAuthDate;

	public CrwCaRspnsId() {
	}

	public CrwCaRspnsId(String crwCaId, String crwClientRef, String crwNcsRefNum, String crwSecId, String crwScaId,
			Integer crwOptnSeq, String crwOptnDesc, BigDecimal crwEligibleQty, BigDecimal crwAdvsdQty, Integer crwSiInd,
			Date crwEntryDt, String crwRmrks, String crwSta, Integer crwStaCd, Integer crwPrevSta, String crwStaDesc,
			BigDecimal crwPndingAproval, BigDecimal crwOvrSubsQty, String crwTndrPricTyp, Integer crwPriceTypCd,
			BigDecimal crwTndrPrice, Date modificationDate, Short crwCaRspnsVer, String crwSecName, String branchid,
			String userid, String crwRjctnRsn, String crwFiller1, String crwFiller5, String crwFiller6,
			BigDecimal crwFiller7, BigDecimal crwFiller8, String crwFiller9, String modifiedby, String crwUpldfilename,
			Short versionnum, String crwAuthby, String crwUniqueCorpRef, String crwBpId, String crwBpName,
			String cancClntRefer, String crwBansrefnum, String crwFunctionofmsg, String crwEvntTyp,
			String bancsinternalid, String crwExtRmrks, String crwPosBucket, BigDecimal crwConditionalQty,
			Date crwAuthDate) {
		this.crwCaId = crwCaId;
		this.crwClientRef = crwClientRef;
		this.crwNcsRefNum = crwNcsRefNum;
		this.crwSecId = crwSecId;
		this.crwScaId = crwScaId;
		this.crwOptnSeq = crwOptnSeq;
		this.crwOptnDesc = crwOptnDesc;
		this.crwEligibleQty = crwEligibleQty;
		this.crwAdvsdQty = crwAdvsdQty;
		this.crwSiInd = crwSiInd;
		this.crwEntryDt = crwEntryDt;
		this.crwRmrks = crwRmrks;
		this.crwSta = crwSta;
		this.crwStaCd = crwStaCd;
		this.crwPrevSta = crwPrevSta;
		this.crwStaDesc = crwStaDesc;
		this.crwPndingAproval = crwPndingAproval;
		this.crwOvrSubsQty = crwOvrSubsQty;
		this.crwTndrPricTyp = crwTndrPricTyp;
		this.crwPriceTypCd = crwPriceTypCd;
		this.crwTndrPrice = crwTndrPrice;
		this.modificationDate = modificationDate;
		this.crwCaRspnsVer = crwCaRspnsVer;
		this.crwSecName = crwSecName;
		this.branchid = branchid;
		this.userid = userid;
		this.crwRjctnRsn = crwRjctnRsn;
		this.crwFiller1 = crwFiller1;
		this.crwFiller5 = crwFiller5;
		this.crwFiller6 = crwFiller6;
		this.crwFiller7 = crwFiller7;
		this.crwFiller8 = crwFiller8;
		this.crwFiller9 = crwFiller9;
		this.modifiedby = modifiedby;
		this.crwUpldfilename = crwUpldfilename;
		this.versionnum = versionnum;
		this.crwAuthby = crwAuthby;
		this.crwUniqueCorpRef = crwUniqueCorpRef;
		this.crwBpId = crwBpId;
		this.crwBpName = crwBpName;
		this.cancClntRefer = cancClntRefer;
		this.crwBansrefnum = crwBansrefnum;
		this.crwFunctionofmsg = crwFunctionofmsg;
		this.crwEvntTyp = crwEvntTyp;
		this.bancsinternalid = bancsinternalid;
		this.crwExtRmrks = crwExtRmrks;
		this.crwPosBucket = crwPosBucket;
		this.crwConditionalQty = crwConditionalQty;
		this.crwAuthDate = crwAuthDate;
	}

	@Column(name = "CRW_CA_ID", length = 16)
	public String getCrwCaId() {
		return this.crwCaId;
	}

	public void setCrwCaId(String crwCaId) {
		this.crwCaId = crwCaId;
	}

	@Column(name = "CRW_CLIENT_REF", length = 18)
	public String getCrwClientRef() {
		return this.crwClientRef;
	}

	public void setCrwClientRef(String crwClientRef) {
		this.crwClientRef = crwClientRef;
	}

	@Column(name = "CRW_NCS_REF_NUM", length = 12)
	public String getCrwNcsRefNum() {
		return this.crwNcsRefNum;
	}

	public void setCrwNcsRefNum(String crwNcsRefNum) {
		this.crwNcsRefNum = crwNcsRefNum;
	}

	@Column(name = "CRW_SEC_ID", length = 36)
	public String getCrwSecId() {
		return this.crwSecId;
	}

	public void setCrwSecId(String crwSecId) {
		this.crwSecId = crwSecId;
	}

	@Column(name = "CRW_SCA_ID", length = 12)
	public String getCrwScaId() {
		return this.crwScaId;
	}

	public void setCrwScaId(String crwScaId) {
		this.crwScaId = crwScaId;
	}

	@Column(name = "CRW_OPTN_SEQ", precision = 8, scale = 0)
	public Integer getCrwOptnSeq() {
		return this.crwOptnSeq;
	}

	public void setCrwOptnSeq(Integer crwOptnSeq) {
		this.crwOptnSeq = crwOptnSeq;
	}

	@Column(name = "CRW_OPTN_DESC", length = 36)
	public String getCrwOptnDesc() {
		return this.crwOptnDesc;
	}

	public void setCrwOptnDesc(String crwOptnDesc) {
		this.crwOptnDesc = crwOptnDesc;
	}

	@Column(name = "CRW_ELIGIBLE_QTY", precision = 36, scale = 4)
	public BigDecimal getCrwEligibleQty() {
		return this.crwEligibleQty;
	}

	public void setCrwEligibleQty(BigDecimal crwEligibleQty) {
		this.crwEligibleQty = crwEligibleQty;
	}

	@Column(name = "CRW_ADVSD_QTY", precision = 36, scale = 4)
	public BigDecimal getCrwAdvsdQty() {
		return this.crwAdvsdQty;
	}

	public void setCrwAdvsdQty(BigDecimal crwAdvsdQty) {
		this.crwAdvsdQty = crwAdvsdQty;
	}

	@Column(name = "CRW_SI_IND", precision = 8, scale = 0)
	public Integer getCrwSiInd() {
		return this.crwSiInd;
	}

	public void setCrwSiInd(Integer crwSiInd) {
		this.crwSiInd = crwSiInd;
	}

	@Column(name = "CRW_ENTRY_DT", length = 13)
	public Date getCrwEntryDt() {
		return this.crwEntryDt;
	}

	public void setCrwEntryDt(Date crwEntryDt) {
		this.crwEntryDt = crwEntryDt;
	}

	@Column(name = "CRW_RMRKS", length = 400)
	public String getCrwRmrks() {
		return this.crwRmrks;
	}

	public void setCrwRmrks(String crwRmrks) {
		this.crwRmrks = crwRmrks;
	}

	@Column(name = "CRW_STA", length = 8)
	public String getCrwSta() {
		return this.crwSta;
	}

	public void setCrwSta(String crwSta) {
		this.crwSta = crwSta;
	}

	@Column(name = "CRW_STA_CD", precision = 8, scale = 0)
	public Integer getCrwStaCd() {
		return this.crwStaCd;
	}

	public void setCrwStaCd(Integer crwStaCd) {
		this.crwStaCd = crwStaCd;
	}

	@Column(name = "CRW_PREV_STA", precision = 8, scale = 0)
	public Integer getCrwPrevSta() {
		return this.crwPrevSta;
	}

	public void setCrwPrevSta(Integer crwPrevSta) {
		this.crwPrevSta = crwPrevSta;
	}

	@Column(name = "CRW_STA_DESC", length = 105)
	public String getCrwStaDesc() {
		return this.crwStaDesc;
	}

	public void setCrwStaDesc(String crwStaDesc) {
		this.crwStaDesc = crwStaDesc;
	}

	@Column(name = "CRW_PNDING_APROVAL", precision = 36, scale = 0)
	public BigDecimal getCrwPndingAproval() {
		return this.crwPndingAproval;
	}

	public void setCrwPndingAproval(BigDecimal crwPndingAproval) {
		this.crwPndingAproval = crwPndingAproval;
	}

	@Column(name = "CRW_OVR_SUBS_QTY", precision = 36, scale = 4)
	public BigDecimal getCrwOvrSubsQty() {
		return this.crwOvrSubsQty;
	}

	public void setCrwOvrSubsQty(BigDecimal crwOvrSubsQty) {
		this.crwOvrSubsQty = crwOvrSubsQty;
	}

	@Column(name = "CRW_TNDR_PRIC_TYP", length = 8)
	public String getCrwTndrPricTyp() {
		return this.crwTndrPricTyp;
	}

	public void setCrwTndrPricTyp(String crwTndrPricTyp) {
		this.crwTndrPricTyp = crwTndrPricTyp;
	}

	@Column(name = "CRW_PRICE_TYP_CD", precision = 8, scale = 0)
	public Integer getCrwPriceTypCd() {
		return this.crwPriceTypCd;
	}

	public void setCrwPriceTypCd(Integer crwPriceTypCd) {
		this.crwPriceTypCd = crwPriceTypCd;
	}

	@Column(name = "CRW_TNDR_PRICE", precision = 15, scale = 6)
	public BigDecimal getCrwTndrPrice() {
		return this.crwTndrPrice;
	}

	public void setCrwTndrPrice(BigDecimal crwTndrPrice) {
		this.crwTndrPrice = crwTndrPrice;
	}

	@Column(name = "MODIFICATION_DATE", length = 13)
	public Date getModificationDate() {
		return this.modificationDate;
	}

	public void setModificationDate(Date modificationDate) {
		this.modificationDate = modificationDate;
	}

	@Column(name = "CRW_CA_RSPNS_VER", precision = 4, scale = 0)
	public Short getCrwCaRspnsVer() {
		return this.crwCaRspnsVer;
	}

	public void setCrwCaRspnsVer(Short crwCaRspnsVer) {
		this.crwCaRspnsVer = crwCaRspnsVer;
	}

	@Column(name = "CRW_SEC_NAME", length = 105)
	public String getCrwSecName() {
		return this.crwSecName;
	}

	public void setCrwSecName(String crwSecName) {
		this.crwSecName = crwSecName;
	}

	@Column(name = "BRANCHID", length = 2)
	public String getBranchid() {
		return this.branchid;
	}

	public void setBranchid(String branchid) {
		this.branchid = branchid;
	}

	@Column(name = "USERID", length = 101)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "CRW_RJCTN_RSN")
	public String getCrwRjctnRsn() {
		return this.crwRjctnRsn;
	}

	public void setCrwRjctnRsn(String crwRjctnRsn) {
		this.crwRjctnRsn = crwRjctnRsn;
	}

	@Column(name = "CRW_FILLER_1", length = 36)
	public String getCrwFiller1() {
		return this.crwFiller1;
	}

	public void setCrwFiller1(String crwFiller1) {
		this.crwFiller1 = crwFiller1;
	}

	@Column(name = "CRW_FILLER_5", length = 20)
	public String getCrwFiller5() {
		return this.crwFiller5;
	}

	public void setCrwFiller5(String crwFiller5) {
		this.crwFiller5 = crwFiller5;
	}

	@Column(name = "CRW_FILLER_6", length = 65)
	public String getCrwFiller6() {
		return this.crwFiller6;
	}

	public void setCrwFiller6(String crwFiller6) {
		this.crwFiller6 = crwFiller6;
	}

	@Column(name = "CRW_FILLER_7", precision = 15, scale = 10)
	public BigDecimal getCrwFiller7() {
		return this.crwFiller7;
	}

	public void setCrwFiller7(BigDecimal crwFiller7) {
		this.crwFiller7 = crwFiller7;
	}

	@Column(name = "CRW_FILLER_8", precision = 18, scale = 4)
	public BigDecimal getCrwFiller8() {
		return this.crwFiller8;
	}

	public void setCrwFiller8(BigDecimal crwFiller8) {
		this.crwFiller8 = crwFiller8;
	}

	@Column(name = "CRW_FILLER_9")
	public String getCrwFiller9() {
		return this.crwFiller9;
	}

	public void setCrwFiller9(String crwFiller9) {
		this.crwFiller9 = crwFiller9;
	}

	@Column(name = "MODIFIEDBY", length = 101)
	public String getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(String modifiedby) {
		this.modifiedby = modifiedby;
	}

	@Column(name = "CRW_UPLDFILENAME", length = 105)
	public String getCrwUpldfilename() {
		return this.crwUpldfilename;
	}

	public void setCrwUpldfilename(String crwUpldfilename) {
		this.crwUpldfilename = crwUpldfilename;
	}

	@Column(name = "VERSIONNUM", precision = 4, scale = 0)
	public Short getVersionnum() {
		return this.versionnum;
	}

	public void setVersionnum(Short versionnum) {
		this.versionnum = versionnum;
	}

	@Column(name = "CRW_AUTHBY", length = 101)
	public String getCrwAuthby() {
		return this.crwAuthby;
	}

	public void setCrwAuthby(String crwAuthby) {
		this.crwAuthby = crwAuthby;
	}

	@Column(name = "CRW_UNIQUE_CORP_REF", length = 70)
	public String getCrwUniqueCorpRef() {
		return this.crwUniqueCorpRef;
	}

	public void setCrwUniqueCorpRef(String crwUniqueCorpRef) {
		this.crwUniqueCorpRef = crwUniqueCorpRef;
	}

	@Column(name = "CRW_BP_ID", length = 16)
	public String getCrwBpId() {
		return this.crwBpId;
	}

	public void setCrwBpId(String crwBpId) {
		this.crwBpId = crwBpId;
	}

	@Column(name = "CRW_BP_NAME", length = 36)
	public String getCrwBpName() {
		return this.crwBpName;
	}

	public void setCrwBpName(String crwBpName) {
		this.crwBpName = crwBpName;
	}

	@Column(name = "CANC_CLNT_REFER", length = 16)
	public String getCancClntRefer() {
		return this.cancClntRefer;
	}

	public void setCancClntRefer(String cancClntRefer) {
		this.cancClntRefer = cancClntRefer;
	}

	@Column(name = "CRW_BANSREFNUM", length = 36)
	public String getCrwBansrefnum() {
		return this.crwBansrefnum;
	}

	public void setCrwBansrefnum(String crwBansrefnum) {
		this.crwBansrefnum = crwBansrefnum;
	}

	@Column(name = "CRW_FUNCTIONOFMSG", length = 4)
	public String getCrwFunctionofmsg() {
		return this.crwFunctionofmsg;
	}

	public void setCrwFunctionofmsg(String crwFunctionofmsg) {
		this.crwFunctionofmsg = crwFunctionofmsg;
	}

	@Column(name = "CRW_EVNT_TYP", length = 40)
	public String getCrwEvntTyp() {
		return this.crwEvntTyp;
	}

	public void setCrwEvntTyp(String crwEvntTyp) {
		this.crwEvntTyp = crwEvntTyp;
	}

	@Column(name = "BANCSINTERNALID", length = 30)
	public String getBancsinternalid() {
		return this.bancsinternalid;
	}

	public void setBancsinternalid(String bancsinternalid) {
		this.bancsinternalid = bancsinternalid;
	}

	@Column(name = "CRW_EXT_RMRKS", length = 400)
	public String getCrwExtRmrks() {
		return this.crwExtRmrks;
	}

	public void setCrwExtRmrks(String crwExtRmrks) {
		this.crwExtRmrks = crwExtRmrks;
	}

	@Column(name = "CRW_POS_BUCKET", length = 10)
	public String getCrwPosBucket() {
		return this.crwPosBucket;
	}

	public void setCrwPosBucket(String crwPosBucket) {
		this.crwPosBucket = crwPosBucket;
	}

	@Column(name = "CRW_CONDITIONAL_QTY", precision = 36, scale = 4)
	public BigDecimal getCrwConditionalQty() {
		return this.crwConditionalQty;
	}

	public void setCrwConditionalQty(BigDecimal crwConditionalQty) {
		this.crwConditionalQty = crwConditionalQty;
	}

	@Column(name = "CRW_AUTH_DATE", length = 13)
	public Date getCrwAuthDate() {
		return this.crwAuthDate;
	}

	public void setCrwAuthDate(Date crwAuthDate) {
		this.crwAuthDate = crwAuthDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CrwCaRspnsId))
			return false;
		CrwCaRspnsId castOther = (CrwCaRspnsId) other;

		return ((this.getCrwCaId() == castOther.getCrwCaId()) || (this.getCrwCaId() != null
				&& castOther.getCrwCaId() != null && this.getCrwCaId().equals(castOther.getCrwCaId())))
				&& ((this.getCrwClientRef() == castOther.getCrwClientRef())
						|| (this.getCrwClientRef() != null && castOther.getCrwClientRef() != null
								&& this.getCrwClientRef().equals(castOther.getCrwClientRef())))
				&& ((this.getCrwNcsRefNum() == castOther.getCrwNcsRefNum())
						|| (this.getCrwNcsRefNum() != null && castOther.getCrwNcsRefNum() != null
								&& this.getCrwNcsRefNum().equals(castOther.getCrwNcsRefNum())))
				&& ((this.getCrwSecId() == castOther.getCrwSecId()) || (this.getCrwSecId() != null
						&& castOther.getCrwSecId() != null && this.getCrwSecId().equals(castOther.getCrwSecId())))
				&& ((this.getCrwScaId() == castOther.getCrwScaId()) || (this.getCrwScaId() != null
						&& castOther.getCrwScaId() != null && this.getCrwScaId().equals(castOther.getCrwScaId())))
				&& ((this.getCrwOptnSeq() == castOther.getCrwOptnSeq()) || (this.getCrwOptnSeq() != null
						&& castOther.getCrwOptnSeq() != null && this.getCrwOptnSeq().equals(castOther.getCrwOptnSeq())))
				&& ((this.getCrwOptnDesc() == castOther.getCrwOptnDesc())
						|| (this.getCrwOptnDesc() != null && castOther.getCrwOptnDesc() != null
								&& this.getCrwOptnDesc().equals(castOther.getCrwOptnDesc())))
				&& ((this.getCrwEligibleQty() == castOther.getCrwEligibleQty())
						|| (this.getCrwEligibleQty() != null && castOther.getCrwEligibleQty() != null
								&& this.getCrwEligibleQty().equals(castOther.getCrwEligibleQty())))
				&& ((this.getCrwAdvsdQty() == castOther.getCrwAdvsdQty())
						|| (this.getCrwAdvsdQty() != null && castOther.getCrwAdvsdQty() != null
								&& this.getCrwAdvsdQty().equals(castOther.getCrwAdvsdQty())))
				&& ((this.getCrwSiInd() == castOther.getCrwSiInd()) || (this.getCrwSiInd() != null
						&& castOther.getCrwSiInd() != null && this.getCrwSiInd().equals(castOther.getCrwSiInd())))
				&& ((this.getCrwEntryDt() == castOther.getCrwEntryDt()) || (this.getCrwEntryDt() != null
						&& castOther.getCrwEntryDt() != null && this.getCrwEntryDt().equals(castOther.getCrwEntryDt())))
				&& ((this.getCrwRmrks() == castOther.getCrwRmrks()) || (this.getCrwRmrks() != null
						&& castOther.getCrwRmrks() != null && this.getCrwRmrks().equals(castOther.getCrwRmrks())))
				&& ((this.getCrwSta() == castOther.getCrwSta()) || (this.getCrwSta() != null
						&& castOther.getCrwSta() != null && this.getCrwSta().equals(castOther.getCrwSta())))
				&& ((this.getCrwStaCd() == castOther.getCrwStaCd()) || (this.getCrwStaCd() != null
						&& castOther.getCrwStaCd() != null && this.getCrwStaCd().equals(castOther.getCrwStaCd())))
				&& ((this.getCrwPrevSta() == castOther.getCrwPrevSta()) || (this.getCrwPrevSta() != null
						&& castOther.getCrwPrevSta() != null && this.getCrwPrevSta().equals(castOther.getCrwPrevSta())))
				&& ((this.getCrwStaDesc() == castOther.getCrwStaDesc()) || (this.getCrwStaDesc() != null
						&& castOther.getCrwStaDesc() != null && this.getCrwStaDesc().equals(castOther.getCrwStaDesc())))
				&& ((this.getCrwPndingAproval() == castOther.getCrwPndingAproval())
						|| (this.getCrwPndingAproval() != null && castOther.getCrwPndingAproval() != null
								&& this.getCrwPndingAproval().equals(castOther.getCrwPndingAproval())))
				&& ((this.getCrwOvrSubsQty() == castOther.getCrwOvrSubsQty())
						|| (this.getCrwOvrSubsQty() != null && castOther.getCrwOvrSubsQty() != null
								&& this.getCrwOvrSubsQty().equals(castOther.getCrwOvrSubsQty())))
				&& ((this.getCrwTndrPricTyp() == castOther.getCrwTndrPricTyp())
						|| (this.getCrwTndrPricTyp() != null && castOther.getCrwTndrPricTyp() != null
								&& this.getCrwTndrPricTyp().equals(castOther.getCrwTndrPricTyp())))
				&& ((this.getCrwPriceTypCd() == castOther.getCrwPriceTypCd())
						|| (this.getCrwPriceTypCd() != null && castOther.getCrwPriceTypCd() != null
								&& this.getCrwPriceTypCd().equals(castOther.getCrwPriceTypCd())))
				&& ((this.getCrwTndrPrice() == castOther.getCrwTndrPrice())
						|| (this.getCrwTndrPrice() != null && castOther.getCrwTndrPrice() != null
								&& this.getCrwTndrPrice().equals(castOther.getCrwTndrPrice())))
				&& ((this.getModificationDate() == castOther.getModificationDate())
						|| (this.getModificationDate() != null && castOther.getModificationDate() != null
								&& this.getModificationDate().equals(castOther.getModificationDate())))
				&& ((this.getCrwCaRspnsVer() == castOther.getCrwCaRspnsVer())
						|| (this.getCrwCaRspnsVer() != null && castOther.getCrwCaRspnsVer() != null
								&& this.getCrwCaRspnsVer().equals(castOther.getCrwCaRspnsVer())))
				&& ((this.getCrwSecName() == castOther.getCrwSecName()) || (this.getCrwSecName() != null
						&& castOther.getCrwSecName() != null && this.getCrwSecName().equals(castOther.getCrwSecName())))
				&& ((this.getBranchid() == castOther.getBranchid()) || (this.getBranchid() != null
						&& castOther.getBranchid() != null && this.getBranchid().equals(castOther.getBranchid())))
				&& ((this.getUserid() == castOther.getUserid()) || (this.getUserid() != null
						&& castOther.getUserid() != null && this.getUserid().equals(castOther.getUserid())))
				&& ((this.getCrwRjctnRsn() == castOther.getCrwRjctnRsn())
						|| (this.getCrwRjctnRsn() != null && castOther.getCrwRjctnRsn() != null
								&& this.getCrwRjctnRsn().equals(castOther.getCrwRjctnRsn())))
				&& ((this.getCrwFiller1() == castOther.getCrwFiller1()) || (this.getCrwFiller1() != null
						&& castOther.getCrwFiller1() != null && this.getCrwFiller1().equals(castOther.getCrwFiller1())))
				&& ((this.getCrwFiller5() == castOther.getCrwFiller5()) || (this.getCrwFiller5() != null
						&& castOther.getCrwFiller5() != null && this.getCrwFiller5().equals(castOther.getCrwFiller5())))
				&& ((this.getCrwFiller6() == castOther.getCrwFiller6()) || (this.getCrwFiller6() != null
						&& castOther.getCrwFiller6() != null && this.getCrwFiller6().equals(castOther.getCrwFiller6())))
				&& ((this.getCrwFiller7() == castOther.getCrwFiller7()) || (this.getCrwFiller7() != null
						&& castOther.getCrwFiller7() != null && this.getCrwFiller7().equals(castOther.getCrwFiller7())))
				&& ((this.getCrwFiller8() == castOther.getCrwFiller8()) || (this.getCrwFiller8() != null
						&& castOther.getCrwFiller8() != null && this.getCrwFiller8().equals(castOther.getCrwFiller8())))
				&& ((this.getCrwFiller9() == castOther.getCrwFiller9()) || (this.getCrwFiller9() != null
						&& castOther.getCrwFiller9() != null && this.getCrwFiller9().equals(castOther.getCrwFiller9())))
				&& ((this.getModifiedby() == castOther.getModifiedby()) || (this.getModifiedby() != null
						&& castOther.getModifiedby() != null && this.getModifiedby().equals(castOther.getModifiedby())))
				&& ((this.getCrwUpldfilename() == castOther.getCrwUpldfilename())
						|| (this.getCrwUpldfilename() != null && castOther.getCrwUpldfilename() != null
								&& this.getCrwUpldfilename().equals(castOther.getCrwUpldfilename())))
				&& ((this.getVersionnum() == castOther.getVersionnum()) || (this.getVersionnum() != null
						&& castOther.getVersionnum() != null && this.getVersionnum().equals(castOther.getVersionnum())))
				&& ((this.getCrwAuthby() == castOther.getCrwAuthby()) || (this.getCrwAuthby() != null
						&& castOther.getCrwAuthby() != null && this.getCrwAuthby().equals(castOther.getCrwAuthby())))
				&& ((this.getCrwUniqueCorpRef() == castOther.getCrwUniqueCorpRef())
						|| (this.getCrwUniqueCorpRef() != null && castOther.getCrwUniqueCorpRef() != null
								&& this.getCrwUniqueCorpRef().equals(castOther.getCrwUniqueCorpRef())))
				&& ((this.getCrwBpId() == castOther.getCrwBpId()) || (this.getCrwBpId() != null
						&& castOther.getCrwBpId() != null && this.getCrwBpId().equals(castOther.getCrwBpId())))
				&& ((this.getCrwBpName() == castOther.getCrwBpName()) || (this.getCrwBpName() != null
						&& castOther.getCrwBpName() != null && this.getCrwBpName().equals(castOther.getCrwBpName())))
				&& ((this.getCancClntRefer() == castOther.getCancClntRefer())
						|| (this.getCancClntRefer() != null && castOther.getCancClntRefer() != null
								&& this.getCancClntRefer().equals(castOther.getCancClntRefer())))
				&& ((this.getCrwBansrefnum() == castOther.getCrwBansrefnum())
						|| (this.getCrwBansrefnum() != null && castOther.getCrwBansrefnum() != null
								&& this.getCrwBansrefnum().equals(castOther.getCrwBansrefnum())))
				&& ((this.getCrwFunctionofmsg() == castOther.getCrwFunctionofmsg())
						|| (this.getCrwFunctionofmsg() != null && castOther.getCrwFunctionofmsg() != null
								&& this.getCrwFunctionofmsg().equals(castOther.getCrwFunctionofmsg())))
				&& ((this.getCrwEvntTyp() == castOther.getCrwEvntTyp()) || (this.getCrwEvntTyp() != null
						&& castOther.getCrwEvntTyp() != null && this.getCrwEvntTyp().equals(castOther.getCrwEvntTyp())))
				&& ((this.getBancsinternalid() == castOther.getBancsinternalid())
						|| (this.getBancsinternalid() != null && castOther.getBancsinternalid() != null
								&& this.getBancsinternalid().equals(castOther.getBancsinternalid())))
				&& ((this.getCrwExtRmrks() == castOther.getCrwExtRmrks())
						|| (this.getCrwExtRmrks() != null && castOther.getCrwExtRmrks() != null
								&& this.getCrwExtRmrks().equals(castOther.getCrwExtRmrks())))
				&& ((this.getCrwPosBucket() == castOther.getCrwPosBucket())
						|| (this.getCrwPosBucket() != null && castOther.getCrwPosBucket() != null
								&& this.getCrwPosBucket().equals(castOther.getCrwPosBucket())))
				&& ((this.getCrwConditionalQty() == castOther.getCrwConditionalQty())
						|| (this.getCrwConditionalQty() != null && castOther.getCrwConditionalQty() != null
								&& this.getCrwConditionalQty().equals(castOther.getCrwConditionalQty())))
				&& ((this.getCrwAuthDate() == castOther.getCrwAuthDate())
						|| (this.getCrwAuthDate() != null && castOther.getCrwAuthDate() != null
								&& this.getCrwAuthDate().equals(castOther.getCrwAuthDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCrwCaId() == null ? 0 : this.getCrwCaId().hashCode());
		result = 37 * result + (getCrwClientRef() == null ? 0 : this.getCrwClientRef().hashCode());
		result = 37 * result + (getCrwNcsRefNum() == null ? 0 : this.getCrwNcsRefNum().hashCode());
		result = 37 * result + (getCrwSecId() == null ? 0 : this.getCrwSecId().hashCode());
		result = 37 * result + (getCrwScaId() == null ? 0 : this.getCrwScaId().hashCode());
		result = 37 * result + (getCrwOptnSeq() == null ? 0 : this.getCrwOptnSeq().hashCode());
		result = 37 * result + (getCrwOptnDesc() == null ? 0 : this.getCrwOptnDesc().hashCode());
		result = 37 * result + (getCrwEligibleQty() == null ? 0 : this.getCrwEligibleQty().hashCode());
		result = 37 * result + (getCrwAdvsdQty() == null ? 0 : this.getCrwAdvsdQty().hashCode());
		result = 37 * result + (getCrwSiInd() == null ? 0 : this.getCrwSiInd().hashCode());
		result = 37 * result + (getCrwEntryDt() == null ? 0 : this.getCrwEntryDt().hashCode());
		result = 37 * result + (getCrwRmrks() == null ? 0 : this.getCrwRmrks().hashCode());
		result = 37 * result + (getCrwSta() == null ? 0 : this.getCrwSta().hashCode());
		result = 37 * result + (getCrwStaCd() == null ? 0 : this.getCrwStaCd().hashCode());
		result = 37 * result + (getCrwPrevSta() == null ? 0 : this.getCrwPrevSta().hashCode());
		result = 37 * result + (getCrwStaDesc() == null ? 0 : this.getCrwStaDesc().hashCode());
		result = 37 * result + (getCrwPndingAproval() == null ? 0 : this.getCrwPndingAproval().hashCode());
		result = 37 * result + (getCrwOvrSubsQty() == null ? 0 : this.getCrwOvrSubsQty().hashCode());
		result = 37 * result + (getCrwTndrPricTyp() == null ? 0 : this.getCrwTndrPricTyp().hashCode());
		result = 37 * result + (getCrwPriceTypCd() == null ? 0 : this.getCrwPriceTypCd().hashCode());
		result = 37 * result + (getCrwTndrPrice() == null ? 0 : this.getCrwTndrPrice().hashCode());
		result = 37 * result + (getModificationDate() == null ? 0 : this.getModificationDate().hashCode());
		result = 37 * result + (getCrwCaRspnsVer() == null ? 0 : this.getCrwCaRspnsVer().hashCode());
		result = 37 * result + (getCrwSecName() == null ? 0 : this.getCrwSecName().hashCode());
		result = 37 * result + (getBranchid() == null ? 0 : this.getBranchid().hashCode());
		result = 37 * result + (getUserid() == null ? 0 : this.getUserid().hashCode());
		result = 37 * result + (getCrwRjctnRsn() == null ? 0 : this.getCrwRjctnRsn().hashCode());
		result = 37 * result + (getCrwFiller1() == null ? 0 : this.getCrwFiller1().hashCode());
		result = 37 * result + (getCrwFiller5() == null ? 0 : this.getCrwFiller5().hashCode());
		result = 37 * result + (getCrwFiller6() == null ? 0 : this.getCrwFiller6().hashCode());
		result = 37 * result + (getCrwFiller7() == null ? 0 : this.getCrwFiller7().hashCode());
		result = 37 * result + (getCrwFiller8() == null ? 0 : this.getCrwFiller8().hashCode());
		result = 37 * result + (getCrwFiller9() == null ? 0 : this.getCrwFiller9().hashCode());
		result = 37 * result + (getModifiedby() == null ? 0 : this.getModifiedby().hashCode());
		result = 37 * result + (getCrwUpldfilename() == null ? 0 : this.getCrwUpldfilename().hashCode());
		result = 37 * result + (getVersionnum() == null ? 0 : this.getVersionnum().hashCode());
		result = 37 * result + (getCrwAuthby() == null ? 0 : this.getCrwAuthby().hashCode());
		result = 37 * result + (getCrwUniqueCorpRef() == null ? 0 : this.getCrwUniqueCorpRef().hashCode());
		result = 37 * result + (getCrwBpId() == null ? 0 : this.getCrwBpId().hashCode());
		result = 37 * result + (getCrwBpName() == null ? 0 : this.getCrwBpName().hashCode());
		result = 37 * result + (getCancClntRefer() == null ? 0 : this.getCancClntRefer().hashCode());
		result = 37 * result + (getCrwBansrefnum() == null ? 0 : this.getCrwBansrefnum().hashCode());
		result = 37 * result + (getCrwFunctionofmsg() == null ? 0 : this.getCrwFunctionofmsg().hashCode());
		result = 37 * result + (getCrwEvntTyp() == null ? 0 : this.getCrwEvntTyp().hashCode());
		result = 37 * result + (getBancsinternalid() == null ? 0 : this.getBancsinternalid().hashCode());
		result = 37 * result + (getCrwExtRmrks() == null ? 0 : this.getCrwExtRmrks().hashCode());
		result = 37 * result + (getCrwPosBucket() == null ? 0 : this.getCrwPosBucket().hashCode());
		result = 37 * result + (getCrwConditionalQty() == null ? 0 : this.getCrwConditionalQty().hashCode());
		result = 37 * result + (getCrwAuthDate() == null ? 0 : this.getCrwAuthDate().hashCode());
		return result;
	}

}
