package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CrwCaResoln generated by hbm2java
 */
@Entity
@Table(name = "crw_ca_resoln", schema = "public")
public class CrwCaResoln implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6800434107154878795L;
	private CrwCaResolnId id;

	public CrwCaResoln() {
	}

	public CrwCaResoln(CrwCaResolnId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "resolNo", column = @Column(name = "resol_no", precision = 2, scale = 0)),
			@AttributeOverride(name = "resolTtl", column = @Column(name = "resol_ttl", length = 4)),
			@AttributeOverride(name = "resolTyp", column = @Column(name = "resol_typ", length = 100)),
			@AttributeOverride(name = "options", column = @Column(name = "options", length = 100)),
			@AttributeOverride(name = "instrQty", column = @Column(name = "instr_qty", precision = 36, scale = 4)),
			@AttributeOverride(name = "crwNcsRefNo", column = @Column(name = "crw_ncs_ref_no", length = 12)),
			@AttributeOverride(name = "crwReslnRandom", column = @Column(name = "crw_resln_random", length = 12)),
			@AttributeOverride(name = "resDesc", column = @Column(name = "res_desc", length = 50)) })
	public CrwCaResolnId getId() {
		return this.id;
	}

	public void setId(CrwCaResolnId id) {
		this.id = id;
	}

}
