package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CrwCaResolnId generated by hbm2java
 */
@Embeddable
public class CrwCaResolnId implements java.io.Serializable {

	private Byte resolNo;
	private String resolTtl;
	private String resolTyp;
	private String options;
	private BigDecimal instrQty;
	private String crwNcsRefNo;
	private String crwReslnRandom;
	private String resDesc;

	public CrwCaResolnId() {
	}

	public CrwCaResolnId(Byte resolNo, String resolTtl, String resolTyp, String options, BigDecimal instrQty,
			String crwNcsRefNo, String crwReslnRandom, String resDesc) {
		this.resolNo = resolNo;
		this.resolTtl = resolTtl;
		this.resolTyp = resolTyp;
		this.options = options;
		this.instrQty = instrQty;
		this.crwNcsRefNo = crwNcsRefNo;
		this.crwReslnRandom = crwReslnRandom;
		this.resDesc = resDesc;
	}

	@Column(name = "resol_no", precision = 2, scale = 0)
	public Byte getResolNo() {
		return this.resolNo;
	}

	public void setResolNo(Byte resolNo) {
		this.resolNo = resolNo;
	}

	@Column(name = "resol_ttl", length = 4)
	public String getResolTtl() {
		return this.resolTtl;
	}

	public void setResolTtl(String resolTtl) {
		this.resolTtl = resolTtl;
	}

	@Column(name = "resol_typ", length = 100)
	public String getResolTyp() {
		return this.resolTyp;
	}

	public void setResolTyp(String resolTyp) {
		this.resolTyp = resolTyp;
	}

	@Column(name = "options", length = 100)
	public String getOptions() {
		return this.options;
	}

	public void setOptions(String options) {
		this.options = options;
	}

	@Column(name = "instr_qty", precision = 36, scale = 4)
	public BigDecimal getInstrQty() {
		return this.instrQty;
	}

	public void setInstrQty(BigDecimal instrQty) {
		this.instrQty = instrQty;
	}

	@Column(name = "crw_ncs_ref_no", length = 12)
	public String getCrwNcsRefNo() {
		return this.crwNcsRefNo;
	}

	public void setCrwNcsRefNo(String crwNcsRefNo) {
		this.crwNcsRefNo = crwNcsRefNo;
	}

	@Column(name = "crw_resln_random", length = 12)
	public String getCrwReslnRandom() {
		return this.crwReslnRandom;
	}

	public void setCrwReslnRandom(String crwReslnRandom) {
		this.crwReslnRandom = crwReslnRandom;
	}

	@Column(name = "res_desc", length = 50)
	public String getResDesc() {
		return this.resDesc;
	}

	public void setResDesc(String resDesc) {
		this.resDesc = resDesc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CrwCaResolnId))
			return false;
		CrwCaResolnId castOther = (CrwCaResolnId) other;

		return ((this.getResolNo() == castOther.getResolNo()) || (this.getResolNo() != null
				&& castOther.getResolNo() != null && this.getResolNo().equals(castOther.getResolNo())))
				&& ((this.getResolTtl() == castOther.getResolTtl()) || (this.getResolTtl() != null
						&& castOther.getResolTtl() != null && this.getResolTtl().equals(castOther.getResolTtl())))
				&& ((this.getResolTyp() == castOther.getResolTyp()) || (this.getResolTyp() != null
						&& castOther.getResolTyp() != null && this.getResolTyp().equals(castOther.getResolTyp())))
				&& ((this.getOptions() == castOther.getOptions()) || (this.getOptions() != null
						&& castOther.getOptions() != null && this.getOptions().equals(castOther.getOptions())))
				&& ((this.getInstrQty() == castOther.getInstrQty()) || (this.getInstrQty() != null
						&& castOther.getInstrQty() != null && this.getInstrQty().equals(castOther.getInstrQty())))
				&& ((this.getCrwNcsRefNo() == castOther.getCrwNcsRefNo())
						|| (this.getCrwNcsRefNo() != null && castOther.getCrwNcsRefNo() != null
								&& this.getCrwNcsRefNo().equals(castOther.getCrwNcsRefNo())))
				&& ((this.getCrwReslnRandom() == castOther.getCrwReslnRandom())
						|| (this.getCrwReslnRandom() != null && castOther.getCrwReslnRandom() != null
								&& this.getCrwReslnRandom().equals(castOther.getCrwReslnRandom())))
				&& ((this.getResDesc() == castOther.getResDesc()) || (this.getResDesc() != null
						&& castOther.getResDesc() != null && this.getResDesc().equals(castOther.getResDesc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getResolNo() == null ? 0 : this.getResolNo().hashCode());
		result = 37 * result + (getResolTtl() == null ? 0 : this.getResolTtl().hashCode());
		result = 37 * result + (getResolTyp() == null ? 0 : this.getResolTyp().hashCode());
		result = 37 * result + (getOptions() == null ? 0 : this.getOptions().hashCode());
		result = 37 * result + (getInstrQty() == null ? 0 : this.getInstrQty().hashCode());
		result = 37 * result + (getCrwNcsRefNo() == null ? 0 : this.getCrwNcsRefNo().hashCode());
		result = 37 * result + (getCrwReslnRandom() == null ? 0 : this.getCrwReslnRandom().hashCode());
		result = 37 * result + (getResDesc() == null ? 0 : this.getResDesc().hashCode());
		return result;
	}

}
