package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CrwCaRspns generated by hbm2java
 */
@Entity
@Table(name = "crw_ca_rspns", schema = "public")
public class CrwCaRspns implements java.io.Serializable {

	private CrwCaRspnsId id;

	public CrwCaRspns() {
	}

	public CrwCaRspns(CrwCaRspnsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "crwCaId", column = @Column(name = "CRW_CA_ID", length = 16)),
			@AttributeOverride(name = "crwClientRef", column = @Column(name = "CRW_CLIENT_REF", length = 18)),
			@AttributeOverride(name = "crwNcsRefNum", column = @Column(name = "CRW_NCS_REF_NUM", length = 12)),
			@AttributeOverride(name = "crwSecId", column = @Column(name = "CRW_SEC_ID", length = 36)),
			@AttributeOverride(name = "crwScaId", column = @Column(name = "CRW_SCA_ID", length = 12)),
			@AttributeOverride(name = "crwOptnSeq", column = @Column(name = "CRW_OPTN_SEQ", precision = 8, scale = 0)),
			@AttributeOverride(name = "crwOptnDesc", column = @Column(name = "CRW_OPTN_DESC", length = 36)),
			@AttributeOverride(name = "crwEligibleQty", column = @Column(name = "CRW_ELIGIBLE_QTY", precision = 36, scale = 4)),
			@AttributeOverride(name = "crwAdvsdQty", column = @Column(name = "CRW_ADVSD_QTY", precision = 36, scale = 4)),
			@AttributeOverride(name = "crwSiInd", column = @Column(name = "CRW_SI_IND", precision = 8, scale = 0)),
			@AttributeOverride(name = "crwEntryDt", column = @Column(name = "CRW_ENTRY_DT", length = 13)),
			@AttributeOverride(name = "crwRmrks", column = @Column(name = "CRW_RMRKS", length = 400)),
			@AttributeOverride(name = "crwSta", column = @Column(name = "CRW_STA", length = 8)),
			@AttributeOverride(name = "crwStaCd", column = @Column(name = "CRW_STA_CD", precision = 8, scale = 0)),
			@AttributeOverride(name = "crwPrevSta", column = @Column(name = "CRW_PREV_STA", precision = 8, scale = 0)),
			@AttributeOverride(name = "crwStaDesc", column = @Column(name = "CRW_STA_DESC", length = 105)),
			@AttributeOverride(name = "crwPndingAproval", column = @Column(name = "CRW_PNDING_APROVAL", precision = 36, scale = 0)),
			@AttributeOverride(name = "crwOvrSubsQty", column = @Column(name = "CRW_OVR_SUBS_QTY", precision = 36, scale = 4)),
			@AttributeOverride(name = "crwTndrPricTyp", column = @Column(name = "CRW_TNDR_PRIC_TYP", length = 8)),
			@AttributeOverride(name = "crwPriceTypCd", column = @Column(name = "CRW_PRICE_TYP_CD", precision = 8, scale = 0)),
			@AttributeOverride(name = "crwTndrPrice", column = @Column(name = "CRW_TNDR_PRICE", precision = 15, scale = 6)),
			@AttributeOverride(name = "modificationDate", column = @Column(name = "MODIFICATION_DATE", length = 13)),
			@AttributeOverride(name = "crwCaRspnsVer", column = @Column(name = "CRW_CA_RSPNS_VER", precision = 4, scale = 0)),
			@AttributeOverride(name = "crwSecName", column = @Column(name = "CRW_SEC_NAME", length = 105)),
			@AttributeOverride(name = "branchid", column = @Column(name = "BRANCHID", length = 2)),
			@AttributeOverride(name = "userid", column = @Column(name = "USERID", length = 101)),
			@AttributeOverride(name = "crwRjctnRsn", column = @Column(name = "CRW_RJCTN_RSN")),
			@AttributeOverride(name = "crwFiller1", column = @Column(name = "CRW_FILLER_1", length = 36)),
			@AttributeOverride(name = "crwFiller5", column = @Column(name = "CRW_FILLER_5", length = 20)),
			@AttributeOverride(name = "crwFiller6", column = @Column(name = "CRW_FILLER_6", length = 65)),
			@AttributeOverride(name = "crwFiller7", column = @Column(name = "CRW_FILLER_7", precision = 15, scale = 10)),
			@AttributeOverride(name = "crwFiller8", column = @Column(name = "CRW_FILLER_8", precision = 18, scale = 4)),
			@AttributeOverride(name = "crwFiller9", column = @Column(name = "CRW_FILLER_9")),
			@AttributeOverride(name = "modifiedby", column = @Column(name = "MODIFIEDBY", length = 101)),
			@AttributeOverride(name = "crwUpldfilename", column = @Column(name = "CRW_UPLDFILENAME", length = 105)),
			@AttributeOverride(name = "versionnum", column = @Column(name = "VERSIONNUM", precision = 4, scale = 0)),
			@AttributeOverride(name = "crwAuthby", column = @Column(name = "CRW_AUTHBY", length = 101)),
			@AttributeOverride(name = "crwUniqueCorpRef", column = @Column(name = "CRW_UNIQUE_CORP_REF", length = 70)),
			@AttributeOverride(name = "crwBpId", column = @Column(name = "CRW_BP_ID", length = 16)),
			@AttributeOverride(name = "crwBpName", column = @Column(name = "CRW_BP_NAME", length = 36)),
			@AttributeOverride(name = "cancClntRefer", column = @Column(name = "CANC_CLNT_REFER", length = 16)),
			@AttributeOverride(name = "crwBansrefnum", column = @Column(name = "CRW_BANSREFNUM", length = 36)),
			@AttributeOverride(name = "crwFunctionofmsg", column = @Column(name = "CRW_FUNCTIONOFMSG", length = 4)),
			@AttributeOverride(name = "crwEvntTyp", column = @Column(name = "CRW_EVNT_TYP", length = 40)),
			@AttributeOverride(name = "bancsinternalid", column = @Column(name = "BANCSINTERNALID", length = 30)),
			@AttributeOverride(name = "crwExtRmrks", column = @Column(name = "CRW_EXT_RMRKS", length = 400)),
			@AttributeOverride(name = "crwPosBucket", column = @Column(name = "CRW_POS_BUCKET", length = 10)),
			@AttributeOverride(name = "crwConditionalQty", column = @Column(name = "CRW_CONDITIONAL_QTY", precision = 36, scale = 4)),
			@AttributeOverride(name = "crwAuthDate", column = @Column(name = "CRW_AUTH_DATE", length = 13)) })
	public CrwCaRspnsId getId() {
		return this.id;
	}

	public void setId(CrwCaRspnsId id) {
		this.id = id;
	}

}
