package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DsBulkimpFilestatus generated by hbm2java
 */
@Entity
@Table(name = "ds_bulkimp_filestatus", schema = "public")
public class DsBulkimpFilestatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2450393833169920819L;
	private DsBulkimpFilestatusId id;

	public DsBulkimpFilestatus() {
	}

	public DsBulkimpFilestatus(DsBulkimpFilestatusId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "bfsfilereferenceno", column = @Column(name = "BFSFILEREFERENCENO", length = 30)),
			@AttributeOverride(name = "bfsgroupid", column = @Column(name = "BFSGROUPID", length = 15)),
			@AttributeOverride(name = "bfsfiletype", column = @Column(name = "BFSFILETYPE", length = 50)),
			@AttributeOverride(name = "bfsdescription", column = @Column(name = "BFSDESCRIPTION")),
			@AttributeOverride(name = "createdby", column = @Column(name = "CREATEDBY", length = 101)),
			@AttributeOverride(name = "createddate", column = @Column(name = "CREATEDDATE", length = 13)),
			@AttributeOverride(name = "modifiedby", column = @Column(name = "MODIFIEDBY", length = 101)),
			@AttributeOverride(name = "modifieddate", column = @Column(name = "MODIFIEDDATE", length = 13)),
			@AttributeOverride(name = "versionnum", column = @Column(name = "VERSIONNUM", precision = 10, scale = 0)),
			@AttributeOverride(name = "bfsorgfilename", column = @Column(name = "BFSORGFILENAME", length = 200)),
			@AttributeOverride(name = "bfsfilehash", column = @Column(name = "BFSFILEHASH", length = 100)),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", length = 25)),
			@AttributeOverride(name = "serviceloc", column = @Column(name = "SERVICELOC", length = 20)),
			@AttributeOverride(name = "filesize", column = @Column(name = "FILESIZE", length = 20)),
			@AttributeOverride(name = "filetype", column = @Column(name = "FILETYPE", length = 20)),
			@AttributeOverride(name = "bfsorgauthfilename", column = @Column(name = "BFSORGAUTHFILENAME", length = 200)),
			@AttributeOverride(name = "authorizeby", column = @Column(name = "AUTHORIZEBY", length = 101)),
			@AttributeOverride(name = "authorizedate", column = @Column(name = "AUTHORIZEDATE", length = 13)),
			@AttributeOverride(name = "transactionno", column = @Column(name = "TRANSACTIONNO", precision = 8, scale = 0)) })
	public DsBulkimpFilestatusId getId() {
		return this.id;
	}

	public void setId(DsBulkimpFilestatusId id) {
		this.id = id;
	}

}
