package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DsCustodyTiStaging generated by hbm2java
 */
@Entity
@Table(name = "ds_custody_ti_staging", schema = "public")
public class DsCustodyTiStaging implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2241958462307095976L;
	private DsCustodyTiStagingId id;

	public DsCustodyTiStaging() {
	}

	public DsCustodyTiStaging(DsCustodyTiStagingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ctitransrefnum", column = @Column(name = "CTITRANSREFNUM", length = 16)),
			@AttributeOverride(name = "ctistatusmesg", column = @Column(name = "CTISTATUSMESG", length = 4)),
			@AttributeOverride(name = "ctigroupid", column = @Column(name = "CTIGROUPID", length = 8)),
			@AttributeOverride(name = "ctiuserid", column = @Column(name = "CTIUSERID", length = 101)),
			@AttributeOverride(name = "ctimessagetype", column = @Column(name = "CTIMESSAGETYPE", length = 5)),
			@AttributeOverride(name = "ctifreeformat", column = @Column(name = "CTIFREEFORMAT", length = 1750)),
			@AttributeOverride(name = "ctiprepdate", column = @Column(name = "CTIPREPDATE", length = 13)),
			@AttributeOverride(name = "ctitradedate", column = @Column(name = "CTITRADEDATE", length = 13)),
			@AttributeOverride(name = "ctivaluedate", column = @Column(name = "CTIVALUEDATE", length = 13)),
			@AttributeOverride(name = "ctidealcurr", column = @Column(name = "CTIDEALCURR", length = 3)),
			@AttributeOverride(name = "ctidealprice", column = @Column(name = "CTIDEALPRICE", precision = 31, scale = 15)),
			@AttributeOverride(name = "ctisecurityname", column = @Column(name = "CTISECURITYNAME", length = 24)),
			@AttributeOverride(name = "ctisecnum", column = @Column(name = "CTISECNUM", length = 36)),
			@AttributeOverride(name = "ctinumscheme", column = @Column(name = "CTINUMSCHEME", length = 8)),
			@AttributeOverride(name = "ctiqtysecurities", column = @Column(name = "CTIQTYSECURITIES", precision = 31, scale = 15)),
			@AttributeOverride(name = "ctiscaid", column = @Column(name = "CTISCAID", length = 15)),
			@AttributeOverride(name = "cticashacc", column = @Column(name = "CTICASHACC", length = 35)),
			@AttributeOverride(name = "cticustodian", column = @Column(name = "CTICUSTODIAN", length = 14)),
			@AttributeOverride(name = "ctiglobalcustodian", column = @Column(name = "CTIGLOBALCUSTODIAN", length = 105)),
			@AttributeOverride(name = "ctibuyer", column = @Column(name = "CTIBUYER", length = 12)),
			@AttributeOverride(name = "ctiseller", column = @Column(name = "CTISELLER", length = 105)),
			@AttributeOverride(name = "ctibeneficiary", column = @Column(name = "CTIBENEFICIARY", length = 15)),
			@AttributeOverride(name = "ctisttlmntcurr", column = @Column(name = "CTISTTLMNTCURR", length = 3)),
			@AttributeOverride(name = "ctisttlmnttype", column = @Column(name = "CTISTTLMNTTYPE", length = 18)),
			@AttributeOverride(name = "ctisttlmntamount", column = @Column(name = "CTISTTLMNTAMOUNT", precision = 31, scale = 15)),
			@AttributeOverride(name = "ctiplacetrade", column = @Column(name = "CTIPLACETRADE", length = 12)),
			@AttributeOverride(name = "cticustomerreference", column = @Column(name = "CTICUSTOMERREFERENCE", length = 16)),
			@AttributeOverride(name = "cticompany", column = @Column(name = "CTICOMPANY", length = 8)),
			@AttributeOverride(name = "ctiaccountcentre", column = @Column(name = "CTIACCOUNTCENTRE", length = 2)),
			@AttributeOverride(name = "ctioldtransrefnum", column = @Column(name = "CTIOLDTRANSREFNUM", length = 16)),
			@AttributeOverride(name = "ctilastupdateddate", column = @Column(name = "CTILASTUPDATEDDATE", length = 13)),
			@AttributeOverride(name = "ctifunctionofmessage", column = @Column(name = "CTIFUNCTIONOFMESSAGE", length = 4)),
			@AttributeOverride(name = "cticreatedby", column = @Column(name = "CTICREATEDBY", length = 101)),
			@AttributeOverride(name = "ctlastupdatedby", column = @Column(name = "CTLASTUPDATEDBY", length = 101)),
			@AttributeOverride(name = "ctiseclongnm1", column = @Column(name = "CTISECLONGNM1", length = 105)),
			@AttributeOverride(name = "ctiseclongnm2", column = @Column(name = "CTISECLONGNM2", length = 105)),
			@AttributeOverride(name = "ctiseclongnm3", column = @Column(name = "CTISECLONGNM3", length = 105)),
			@AttributeOverride(name = "ctiseclongnm4", column = @Column(name = "CTISECLONGNM4", length = 105)),
			@AttributeOverride(name = "ctibuyerflg", column = @Column(name = "CTIBUYERFLG", length = 1)),
			@AttributeOverride(name = "ctisellerflg", column = @Column(name = "CTISELLERFLG", length = 1)),
			@AttributeOverride(name = "ctichargeacc", column = @Column(name = "CTICHARGEACC", length = 36)),
			@AttributeOverride(name = "bfsfilereferenceno", column = @Column(name = "BFSFILEREFERENCENO", length = 20)),
			@AttributeOverride(name = "ctiauthby", column = @Column(name = "CTIAUTHBY", length = 101)),
			@AttributeOverride(name = "clientname", column = @Column(name = "CLIENTNAME", length = 105)),
			@AttributeOverride(name = "ctirecdelagntname", column = @Column(name = "CTIRECDELAGNTNAME", length = 105)),
			@AttributeOverride(name = "cticlient", column = @Column(name = "CTICLIENT", length = 20)),
			@AttributeOverride(name = "ctiTranRefNum", column = @Column(name = "CTI_TRAN_REF_NUM", length = 12)),
			@AttributeOverride(name = "ctiagent", column = @Column(name = "CTIAGENT", length = 20)),
			@AttributeOverride(name = "ctidealamount", column = @Column(name = "CTIDEALAMOUNT", length = 37)),
			@AttributeOverride(name = "ctiupldfilename", column = @Column(name = "CTIUPLDFILENAME", length = 105)),
			@AttributeOverride(name = "versionnum", column = @Column(name = "VERSIONNUM", precision = 4, scale = 0)),
			@AttributeOverride(name = "secidenscheme", column = @Column(name = "SECIDENSCHEME", precision = 131089, scale = 0)),
			@AttributeOverride(name = "cticlienttype", column = @Column(name = "CTICLIENTTYPE", precision = 131089, scale = 0)),
			@AttributeOverride(name = "ctilclbrkramt", column = @Column(name = "CTILCLBRKRAMT", precision = 31, scale = 15)),
			@AttributeOverride(name = "ctiacrdintamt", column = @Column(name = "CTIACRDINTAMT", precision = 31, scale = 15)),
			@AttributeOverride(name = "ctisttpybind", column = @Column(name = "CTISTTPYBIND", length = 1)),
			@AttributeOverride(name = "cticoboind", column = @Column(name = "CTICOBOIND", length = 1)),
			@AttributeOverride(name = "ctiexmptioncode", column = @Column(name = "CTIEXMPTIONCODE", length = 6)),
			@AttributeOverride(name = "ctibuyrsellbpid", column = @Column(name = "CTIBUYRSELLBPID", length = 15)),
			@AttributeOverride(name = "cticprtybpid", column = @Column(name = "CTICPRTYBPID", length = 15)),
			@AttributeOverride(name = "ctilclbrkrcur", column = @Column(name = "CTILCLBRKRCUR", length = 3)),
			@AttributeOverride(name = "ctiacrdintcur", column = @Column(name = "CTIACRDINTCUR", length = 3)),
			@AttributeOverride(name = "ctiauthind", column = @Column(name = "CTIAUTHIND", precision = 3, scale = 0)),
			@AttributeOverride(name = "ctiordrid", column = @Column(name = "CTIORDRID", precision = 9, scale = 0)),
			@AttributeOverride(name = "mcDeleteTs", column = @Column(name = "MC_DELETE_TS", length = 13)),
			@AttributeOverride(name = "dsCustodyTiStagingVer", column = @Column(name = "DS_CUSTODY_TI_STAGING_VER", precision = 4, scale = 0)),
			@AttributeOverride(name = "dmLstupddt", column = @Column(name = "DM_LSTUPDDT", length = 13)),
			@AttributeOverride(name = "ctipstbpid", column = @Column(name = "CTIPSTBPID", length = 15)),
			@AttributeOverride(name = "ctitranstype", column = @Column(name = "CTITRANSTYPE", length = 4)),
			@AttributeOverride(name = "ctisttpayable", column = @Column(name = "CTISTTPAYABLE", precision = 31, scale = 15)),
			@AttributeOverride(name = "ctiErrorMessage", column = @Column(name = "CTI_ERROR_MESSAGE", length = 4000)),
			@AttributeOverride(name = "ctiipoInd", column = @Column(name = "CTIIPO_IND", length = 1)),
			@AttributeOverride(name = "ctiplref", column = @Column(name = "CTIPLREF", length = 35)),
			@AttributeOverride(name = "dmBtnumeric", column = @Column(name = "DM_BTNUMERIC", precision = 10, scale = 0)),
			@AttributeOverride(name = "dmBtid", column = @Column(name = "DM_BTID", precision = 5, scale = 0)),
			@AttributeOverride(name = "dmUserid", column = @Column(name = "DM_USERID", precision = 8, scale = 0)),
			@AttributeOverride(name = "dmWsid", column = @Column(name = "DM_WSID", precision = 4, scale = 0)),
			@AttributeOverride(name = "ctibyrsllrbic", column = @Column(name = "CTIBYRSLLRBIC", length = 12)),
			@AttributeOverride(name = "buyersellertype", column = @Column(name = "BUYERSELLERTYPE", length = 2)),
			@AttributeOverride(name = "counterpartytype", column = @Column(name = "COUNTERPARTYTYPE", length = 2)),
			@AttributeOverride(name = "cticprtybic", column = @Column(name = "CTICPRTYBIC", length = 12)),
			@AttributeOverride(name = "ctircvdlvcstdnacc", column = @Column(name = "CTIRCVDLVCSTDNACC", length = 35)),
			@AttributeOverride(name = "ctiagntaccinst", column = @Column(name = "CTIAGNTACCINST", length = 35)),
			@AttributeOverride(name = "ctibyrsllracc", column = @Column(name = "CTIBYRSLLRACC", length = 35)),
			@AttributeOverride(name = "ctipsettype", column = @Column(name = "CTIPSETTYPE", length = 2)),
			@AttributeOverride(name = "ctipsetbic", column = @Column(name = "CTIPSETBIC", length = 14)),
			@AttributeOverride(name = "ctiagenttype", column = @Column(name = "CTIAGENTTYPE", length = 2)),
			@AttributeOverride(name = "ctiagentbic", column = @Column(name = "CTIAGENTBIC", length = 14)) })
	public DsCustodyTiStagingId getId() {
		return this.id;
	}

	public void setId(DsCustodyTiStagingId id) {
		this.id = id;
	}

}
