package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DsCustodyTiStagingId generated by hbm2java
 */
@Embeddable
public class DsCustodyTiStagingId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6956573539457876515L;
	private String ctitransrefnum;
	private String ctistatusmesg;
	private String ctigroupid;
	private String ctiuserid;
	private String ctimessagetype;
	private String ctifreeformat;
	private Date ctiprepdate;
	private Date ctitradedate;
	private Date ctivaluedate;
	private String ctidealcurr;
	private BigDecimal ctidealprice;
	private String ctisecurityname;
	private String ctisecnum;
	private String ctinumscheme;
	private BigDecimal ctiqtysecurities;
	private String ctiscaid;
	private String cticashacc;
	private String cticustodian;
	private String ctiglobalcustodian;
	private String ctibuyer;
	private String ctiseller;
	private String ctibeneficiary;
	private String ctisttlmntcurr;
	private String ctisttlmnttype;
	private BigDecimal ctisttlmntamount;
	private String ctiplacetrade;
	private String cticustomerreference;
	private String cticompany;
	private String ctiaccountcentre;
	private String ctioldtransrefnum;
	private Date ctilastupdateddate;
	private String ctifunctionofmessage;
	private String cticreatedby;
	private String ctlastupdatedby;
	private String ctiseclongnm1;
	private String ctiseclongnm2;
	private String ctiseclongnm3;
	private String ctiseclongnm4;
	private String ctibuyerflg;
	private String ctisellerflg;
	private String ctichargeacc;
	private String bfsfilereferenceno;
	private String ctiauthby;
	private String clientname;
	private String ctirecdelagntname;
	private String cticlient;
	private String ctiTranRefNum;
	private String ctiagent;
	private String ctidealamount;
	private String ctiupldfilename;
	private Short versionnum;
	private BigDecimal secidenscheme;
	private BigDecimal cticlienttype;
	private BigDecimal ctilclbrkramt;
	private BigDecimal ctiacrdintamt;
	private String ctisttpybind;
	private String cticoboind;
	private String ctiexmptioncode;
	private String ctibuyrsellbpid;
	private String cticprtybpid;
	private String ctilclbrkrcur;
	private String ctiacrdintcur;
	private Short ctiauthind;
	private Integer ctiordrid;
	private Date mcDeleteTs;
	private Short dsCustodyTiStagingVer;
	private Date dmLstupddt;
	private String ctipstbpid;
	private String ctitranstype;
	private BigDecimal ctisttpayable;
	private String ctiErrorMessage;
	private String ctiipoInd;
	private String ctiplref;
	private Long dmBtnumeric;
	private Integer dmBtid;
	private Integer dmUserid;
	private Short dmWsid;
	private String ctibyrsllrbic;
	private String buyersellertype;
	private String counterpartytype;
	private String cticprtybic;
	private String ctircvdlvcstdnacc;
	private String ctiagntaccinst;
	private String ctibyrsllracc;
	private String ctipsettype;
	private String ctipsetbic;
	private String ctiagenttype;
	private String ctiagentbic;

	public DsCustodyTiStagingId() {
	}

	public DsCustodyTiStagingId(String ctitransrefnum, String ctistatusmesg, String ctigroupid, String ctiuserid,
			String ctimessagetype, String ctifreeformat, Date ctiprepdate, Date ctitradedate, Date ctivaluedate,
			String ctidealcurr, BigDecimal ctidealprice, String ctisecurityname, String ctisecnum, String ctinumscheme,
			BigDecimal ctiqtysecurities, String ctiscaid, String cticashacc, String cticustodian,
			String ctiglobalcustodian, String ctibuyer, String ctiseller, String ctibeneficiary, String ctisttlmntcurr,
			String ctisttlmnttype, BigDecimal ctisttlmntamount, String ctiplacetrade, String cticustomerreference,
			String cticompany, String ctiaccountcentre, String ctioldtransrefnum, Date ctilastupdateddate,
			String ctifunctionofmessage, String cticreatedby, String ctlastupdatedby, String ctiseclongnm1,
			String ctiseclongnm2, String ctiseclongnm3, String ctiseclongnm4, String ctibuyerflg, String ctisellerflg,
			String ctichargeacc, String bfsfilereferenceno, String ctiauthby, String clientname,
			String ctirecdelagntname, String cticlient, String ctiTranRefNum, String ctiagent, String ctidealamount,
			String ctiupldfilename, Short versionnum, BigDecimal secidenscheme, BigDecimal cticlienttype,
			BigDecimal ctilclbrkramt, BigDecimal ctiacrdintamt, String ctisttpybind, String cticoboind,
			String ctiexmptioncode, String ctibuyrsellbpid, String cticprtybpid, String ctilclbrkrcur,
			String ctiacrdintcur, Short ctiauthind, Integer ctiordrid, Date mcDeleteTs, Short dsCustodyTiStagingVer,
			Date dmLstupddt, String ctipstbpid, String ctitranstype, BigDecimal ctisttpayable, String ctiErrorMessage,
			String ctiipoInd, String ctiplref, Long dmBtnumeric, Integer dmBtid, Integer dmUserid, Short dmWsid,
			String ctibyrsllrbic, String buyersellertype, String counterpartytype, String cticprtybic,
			String ctircvdlvcstdnacc, String ctiagntaccinst, String ctibyrsllracc, String ctipsettype,
			String ctipsetbic, String ctiagenttype, String ctiagentbic) {
		this.ctitransrefnum = ctitransrefnum;
		this.ctistatusmesg = ctistatusmesg;
		this.ctigroupid = ctigroupid;
		this.ctiuserid = ctiuserid;
		this.ctimessagetype = ctimessagetype;
		this.ctifreeformat = ctifreeformat;
		this.ctiprepdate = ctiprepdate;
		this.ctitradedate = ctitradedate;
		this.ctivaluedate = ctivaluedate;
		this.ctidealcurr = ctidealcurr;
		this.ctidealprice = ctidealprice;
		this.ctisecurityname = ctisecurityname;
		this.ctisecnum = ctisecnum;
		this.ctinumscheme = ctinumscheme;
		this.ctiqtysecurities = ctiqtysecurities;
		this.ctiscaid = ctiscaid;
		this.cticashacc = cticashacc;
		this.cticustodian = cticustodian;
		this.ctiglobalcustodian = ctiglobalcustodian;
		this.ctibuyer = ctibuyer;
		this.ctiseller = ctiseller;
		this.ctibeneficiary = ctibeneficiary;
		this.ctisttlmntcurr = ctisttlmntcurr;
		this.ctisttlmnttype = ctisttlmnttype;
		this.ctisttlmntamount = ctisttlmntamount;
		this.ctiplacetrade = ctiplacetrade;
		this.cticustomerreference = cticustomerreference;
		this.cticompany = cticompany;
		this.ctiaccountcentre = ctiaccountcentre;
		this.ctioldtransrefnum = ctioldtransrefnum;
		this.ctilastupdateddate = ctilastupdateddate;
		this.ctifunctionofmessage = ctifunctionofmessage;
		this.cticreatedby = cticreatedby;
		this.ctlastupdatedby = ctlastupdatedby;
		this.ctiseclongnm1 = ctiseclongnm1;
		this.ctiseclongnm2 = ctiseclongnm2;
		this.ctiseclongnm3 = ctiseclongnm3;
		this.ctiseclongnm4 = ctiseclongnm4;
		this.ctibuyerflg = ctibuyerflg;
		this.ctisellerflg = ctisellerflg;
		this.ctichargeacc = ctichargeacc;
		this.bfsfilereferenceno = bfsfilereferenceno;
		this.ctiauthby = ctiauthby;
		this.clientname = clientname;
		this.ctirecdelagntname = ctirecdelagntname;
		this.cticlient = cticlient;
		this.ctiTranRefNum = ctiTranRefNum;
		this.ctiagent = ctiagent;
		this.ctidealamount = ctidealamount;
		this.ctiupldfilename = ctiupldfilename;
		this.versionnum = versionnum;
		this.secidenscheme = secidenscheme;
		this.cticlienttype = cticlienttype;
		this.ctilclbrkramt = ctilclbrkramt;
		this.ctiacrdintamt = ctiacrdintamt;
		this.ctisttpybind = ctisttpybind;
		this.cticoboind = cticoboind;
		this.ctiexmptioncode = ctiexmptioncode;
		this.ctibuyrsellbpid = ctibuyrsellbpid;
		this.cticprtybpid = cticprtybpid;
		this.ctilclbrkrcur = ctilclbrkrcur;
		this.ctiacrdintcur = ctiacrdintcur;
		this.ctiauthind = ctiauthind;
		this.ctiordrid = ctiordrid;
		this.mcDeleteTs = mcDeleteTs;
		this.dsCustodyTiStagingVer = dsCustodyTiStagingVer;
		this.dmLstupddt = dmLstupddt;
		this.ctipstbpid = ctipstbpid;
		this.ctitranstype = ctitranstype;
		this.ctisttpayable = ctisttpayable;
		this.ctiErrorMessage = ctiErrorMessage;
		this.ctiipoInd = ctiipoInd;
		this.ctiplref = ctiplref;
		this.dmBtnumeric = dmBtnumeric;
		this.dmBtid = dmBtid;
		this.dmUserid = dmUserid;
		this.dmWsid = dmWsid;
		this.ctibyrsllrbic = ctibyrsllrbic;
		this.buyersellertype = buyersellertype;
		this.counterpartytype = counterpartytype;
		this.cticprtybic = cticprtybic;
		this.ctircvdlvcstdnacc = ctircvdlvcstdnacc;
		this.ctiagntaccinst = ctiagntaccinst;
		this.ctibyrsllracc = ctibyrsllracc;
		this.ctipsettype = ctipsettype;
		this.ctipsetbic = ctipsetbic;
		this.ctiagenttype = ctiagenttype;
		this.ctiagentbic = ctiagentbic;
	}

	@Column(name = "CTITRANSREFNUM", length = 16)
	public String getCtitransrefnum() {
		return this.ctitransrefnum;
	}

	public void setCtitransrefnum(String ctitransrefnum) {
		this.ctitransrefnum = ctitransrefnum;
	}

	@Column(name = "CTISTATUSMESG", length = 4)
	public String getCtistatusmesg() {
		return this.ctistatusmesg;
	}

	public void setCtistatusmesg(String ctistatusmesg) {
		this.ctistatusmesg = ctistatusmesg;
	}

	@Column(name = "CTIGROUPID", length = 8)
	public String getCtigroupid() {
		return this.ctigroupid;
	}

	public void setCtigroupid(String ctigroupid) {
		this.ctigroupid = ctigroupid;
	}

	@Column(name = "CTIUSERID", length = 101)
	public String getCtiuserid() {
		return this.ctiuserid;
	}

	public void setCtiuserid(String ctiuserid) {
		this.ctiuserid = ctiuserid;
	}

	@Column(name = "CTIMESSAGETYPE", length = 5)
	public String getCtimessagetype() {
		return this.ctimessagetype;
	}

	public void setCtimessagetype(String ctimessagetype) {
		this.ctimessagetype = ctimessagetype;
	}

	@Column(name = "CTIFREEFORMAT", length = 1750)
	public String getCtifreeformat() {
		return this.ctifreeformat;
	}

	public void setCtifreeformat(String ctifreeformat) {
		this.ctifreeformat = ctifreeformat;
	}

	@Column(name = "CTIPREPDATE", length = 13)
	public Date getCtiprepdate() {
		return this.ctiprepdate;
	}

	public void setCtiprepdate(Date ctiprepdate) {
		this.ctiprepdate = ctiprepdate;
	}

	@Column(name = "CTITRADEDATE", length = 13)
	public Date getCtitradedate() {
		return this.ctitradedate;
	}

	public void setCtitradedate(Date ctitradedate) {
		this.ctitradedate = ctitradedate;
	}

	@Column(name = "CTIVALUEDATE", length = 13)
	public Date getCtivaluedate() {
		return this.ctivaluedate;
	}

	public void setCtivaluedate(Date ctivaluedate) {
		this.ctivaluedate = ctivaluedate;
	}

	@Column(name = "CTIDEALCURR", length = 3)
	public String getCtidealcurr() {
		return this.ctidealcurr;
	}

	public void setCtidealcurr(String ctidealcurr) {
		this.ctidealcurr = ctidealcurr;
	}

	@Column(name = "CTIDEALPRICE", precision = 31, scale = 15)
	public BigDecimal getCtidealprice() {
		return this.ctidealprice;
	}

	public void setCtidealprice(BigDecimal ctidealprice) {
		this.ctidealprice = ctidealprice;
	}

	@Column(name = "CTISECURITYNAME", length = 24)
	public String getCtisecurityname() {
		return this.ctisecurityname;
	}

	public void setCtisecurityname(String ctisecurityname) {
		this.ctisecurityname = ctisecurityname;
	}

	@Column(name = "CTISECNUM", length = 36)
	public String getCtisecnum() {
		return this.ctisecnum;
	}

	public void setCtisecnum(String ctisecnum) {
		this.ctisecnum = ctisecnum;
	}

	@Column(name = "CTINUMSCHEME", length = 8)
	public String getCtinumscheme() {
		return this.ctinumscheme;
	}

	public void setCtinumscheme(String ctinumscheme) {
		this.ctinumscheme = ctinumscheme;
	}

	@Column(name = "CTIQTYSECURITIES", precision = 31, scale = 15)
	public BigDecimal getCtiqtysecurities() {
		return this.ctiqtysecurities;
	}

	public void setCtiqtysecurities(BigDecimal ctiqtysecurities) {
		this.ctiqtysecurities = ctiqtysecurities;
	}

	@Column(name = "CTISCAID", length = 15)
	public String getCtiscaid() {
		return this.ctiscaid;
	}

	public void setCtiscaid(String ctiscaid) {
		this.ctiscaid = ctiscaid;
	}

	@Column(name = "CTICASHACC", length = 35)
	public String getCticashacc() {
		return this.cticashacc;
	}

	public void setCticashacc(String cticashacc) {
		this.cticashacc = cticashacc;
	}

	@Column(name = "CTICUSTODIAN", length = 14)
	public String getCticustodian() {
		return this.cticustodian;
	}

	public void setCticustodian(String cticustodian) {
		this.cticustodian = cticustodian;
	}

	@Column(name = "CTIGLOBALCUSTODIAN", length = 105)
	public String getCtiglobalcustodian() {
		return this.ctiglobalcustodian;
	}

	public void setCtiglobalcustodian(String ctiglobalcustodian) {
		this.ctiglobalcustodian = ctiglobalcustodian;
	}

	@Column(name = "CTIBUYER", length = 12)
	public String getCtibuyer() {
		return this.ctibuyer;
	}

	public void setCtibuyer(String ctibuyer) {
		this.ctibuyer = ctibuyer;
	}

	@Column(name = "CTISELLER", length = 105)
	public String getCtiseller() {
		return this.ctiseller;
	}

	public void setCtiseller(String ctiseller) {
		this.ctiseller = ctiseller;
	}

	@Column(name = "CTIBENEFICIARY", length = 15)
	public String getCtibeneficiary() {
		return this.ctibeneficiary;
	}

	public void setCtibeneficiary(String ctibeneficiary) {
		this.ctibeneficiary = ctibeneficiary;
	}

	@Column(name = "CTISTTLMNTCURR", length = 3)
	public String getCtisttlmntcurr() {
		return this.ctisttlmntcurr;
	}

	public void setCtisttlmntcurr(String ctisttlmntcurr) {
		this.ctisttlmntcurr = ctisttlmntcurr;
	}

	@Column(name = "CTISTTLMNTTYPE", length = 18)
	public String getCtisttlmnttype() {
		return this.ctisttlmnttype;
	}

	public void setCtisttlmnttype(String ctisttlmnttype) {
		this.ctisttlmnttype = ctisttlmnttype;
	}

	@Column(name = "CTISTTLMNTAMOUNT", precision = 31, scale = 15)
	public BigDecimal getCtisttlmntamount() {
		return this.ctisttlmntamount;
	}

	public void setCtisttlmntamount(BigDecimal ctisttlmntamount) {
		this.ctisttlmntamount = ctisttlmntamount;
	}

	@Column(name = "CTIPLACETRADE", length = 12)
	public String getCtiplacetrade() {
		return this.ctiplacetrade;
	}

	public void setCtiplacetrade(String ctiplacetrade) {
		this.ctiplacetrade = ctiplacetrade;
	}

	@Column(name = "CTICUSTOMERREFERENCE", length = 16)
	public String getCticustomerreference() {
		return this.cticustomerreference;
	}

	public void setCticustomerreference(String cticustomerreference) {
		this.cticustomerreference = cticustomerreference;
	}

	@Column(name = "CTICOMPANY", length = 8)
	public String getCticompany() {
		return this.cticompany;
	}

	public void setCticompany(String cticompany) {
		this.cticompany = cticompany;
	}

	@Column(name = "CTIACCOUNTCENTRE", length = 2)
	public String getCtiaccountcentre() {
		return this.ctiaccountcentre;
	}

	public void setCtiaccountcentre(String ctiaccountcentre) {
		this.ctiaccountcentre = ctiaccountcentre;
	}

	@Column(name = "CTIOLDTRANSREFNUM", length = 16)
	public String getCtioldtransrefnum() {
		return this.ctioldtransrefnum;
	}

	public void setCtioldtransrefnum(String ctioldtransrefnum) {
		this.ctioldtransrefnum = ctioldtransrefnum;
	}

	@Column(name = "CTILASTUPDATEDDATE", length = 13)
	public Date getCtilastupdateddate() {
		return this.ctilastupdateddate;
	}

	public void setCtilastupdateddate(Date ctilastupdateddate) {
		this.ctilastupdateddate = ctilastupdateddate;
	}

	@Column(name = "CTIFUNCTIONOFMESSAGE", length = 4)
	public String getCtifunctionofmessage() {
		return this.ctifunctionofmessage;
	}

	public void setCtifunctionofmessage(String ctifunctionofmessage) {
		this.ctifunctionofmessage = ctifunctionofmessage;
	}

	@Column(name = "CTICREATEDBY", length = 101)
	public String getCticreatedby() {
		return this.cticreatedby;
	}

	public void setCticreatedby(String cticreatedby) {
		this.cticreatedby = cticreatedby;
	}

	@Column(name = "CTLASTUPDATEDBY", length = 101)
	public String getCtlastupdatedby() {
		return this.ctlastupdatedby;
	}

	public void setCtlastupdatedby(String ctlastupdatedby) {
		this.ctlastupdatedby = ctlastupdatedby;
	}

	@Column(name = "CTISECLONGNM1", length = 105)
	public String getCtiseclongnm1() {
		return this.ctiseclongnm1;
	}

	public void setCtiseclongnm1(String ctiseclongnm1) {
		this.ctiseclongnm1 = ctiseclongnm1;
	}

	@Column(name = "CTISECLONGNM2", length = 105)
	public String getCtiseclongnm2() {
		return this.ctiseclongnm2;
	}

	public void setCtiseclongnm2(String ctiseclongnm2) {
		this.ctiseclongnm2 = ctiseclongnm2;
	}

	@Column(name = "CTISECLONGNM3", length = 105)
	public String getCtiseclongnm3() {
		return this.ctiseclongnm3;
	}

	public void setCtiseclongnm3(String ctiseclongnm3) {
		this.ctiseclongnm3 = ctiseclongnm3;
	}

	@Column(name = "CTISECLONGNM4", length = 105)
	public String getCtiseclongnm4() {
		return this.ctiseclongnm4;
	}

	public void setCtiseclongnm4(String ctiseclongnm4) {
		this.ctiseclongnm4 = ctiseclongnm4;
	}

	@Column(name = "CTIBUYERFLG", length = 1)
	public String getCtibuyerflg() {
		return this.ctibuyerflg;
	}

	public void setCtibuyerflg(String ctibuyerflg) {
		this.ctibuyerflg = ctibuyerflg;
	}

	@Column(name = "CTISELLERFLG", length = 1)
	public String getCtisellerflg() {
		return this.ctisellerflg;
	}

	public void setCtisellerflg(String ctisellerflg) {
		this.ctisellerflg = ctisellerflg;
	}

	@Column(name = "CTICHARGEACC", length = 36)
	public String getCtichargeacc() {
		return this.ctichargeacc;
	}

	public void setCtichargeacc(String ctichargeacc) {
		this.ctichargeacc = ctichargeacc;
	}

	@Column(name = "BFSFILEREFERENCENO", length = 20)
	public String getBfsfilereferenceno() {
		return this.bfsfilereferenceno;
	}

	public void setBfsfilereferenceno(String bfsfilereferenceno) {
		this.bfsfilereferenceno = bfsfilereferenceno;
	}

	@Column(name = "CTIAUTHBY", length = 101)
	public String getCtiauthby() {
		return this.ctiauthby;
	}

	public void setCtiauthby(String ctiauthby) {
		this.ctiauthby = ctiauthby;
	}

	@Column(name = "CLIENTNAME", length = 105)
	public String getClientname() {
		return this.clientname;
	}

	public void setClientname(String clientname) {
		this.clientname = clientname;
	}

	@Column(name = "CTIRECDELAGNTNAME", length = 105)
	public String getCtirecdelagntname() {
		return this.ctirecdelagntname;
	}

	public void setCtirecdelagntname(String ctirecdelagntname) {
		this.ctirecdelagntname = ctirecdelagntname;
	}

	@Column(name = "CTICLIENT", length = 20)
	public String getCticlient() {
		return this.cticlient;
	}

	public void setCticlient(String cticlient) {
		this.cticlient = cticlient;
	}

	@Column(name = "CTI_TRAN_REF_NUM", length = 12)
	public String getCtiTranRefNum() {
		return this.ctiTranRefNum;
	}

	public void setCtiTranRefNum(String ctiTranRefNum) {
		this.ctiTranRefNum = ctiTranRefNum;
	}

	@Column(name = "CTIAGENT", length = 20)
	public String getCtiagent() {
		return this.ctiagent;
	}

	public void setCtiagent(String ctiagent) {
		this.ctiagent = ctiagent;
	}

	@Column(name = "CTIDEALAMOUNT", length = 37)
	public String getCtidealamount() {
		return this.ctidealamount;
	}

	public void setCtidealamount(String ctidealamount) {
		this.ctidealamount = ctidealamount;
	}

	@Column(name = "CTIUPLDFILENAME", length = 105)
	public String getCtiupldfilename() {
		return this.ctiupldfilename;
	}

	public void setCtiupldfilename(String ctiupldfilename) {
		this.ctiupldfilename = ctiupldfilename;
	}

	@Column(name = "VERSIONNUM", precision = 4, scale = 0)
	public Short getVersionnum() {
		return this.versionnum;
	}

	public void setVersionnum(Short versionnum) {
		this.versionnum = versionnum;
	}

	@Column(name = "SECIDENSCHEME", precision = 131089, scale = 0)
	public BigDecimal getSecidenscheme() {
		return this.secidenscheme;
	}

	public void setSecidenscheme(BigDecimal secidenscheme) {
		this.secidenscheme = secidenscheme;
	}

	@Column(name = "CTICLIENTTYPE", precision = 131089, scale = 0)
	public BigDecimal getCticlienttype() {
		return this.cticlienttype;
	}

	public void setCticlienttype(BigDecimal cticlienttype) {
		this.cticlienttype = cticlienttype;
	}

	@Column(name = "CTILCLBRKRAMT", precision = 31, scale = 15)
	public BigDecimal getCtilclbrkramt() {
		return this.ctilclbrkramt;
	}

	public void setCtilclbrkramt(BigDecimal ctilclbrkramt) {
		this.ctilclbrkramt = ctilclbrkramt;
	}

	@Column(name = "CTIACRDINTAMT", precision = 31, scale = 15)
	public BigDecimal getCtiacrdintamt() {
		return this.ctiacrdintamt;
	}

	public void setCtiacrdintamt(BigDecimal ctiacrdintamt) {
		this.ctiacrdintamt = ctiacrdintamt;
	}

	@Column(name = "CTISTTPYBIND", length = 1)
	public String getCtisttpybind() {
		return this.ctisttpybind;
	}

	public void setCtisttpybind(String ctisttpybind) {
		this.ctisttpybind = ctisttpybind;
	}

	@Column(name = "CTICOBOIND", length = 1)
	public String getCticoboind() {
		return this.cticoboind;
	}

	public void setCticoboind(String cticoboind) {
		this.cticoboind = cticoboind;
	}

	@Column(name = "CTIEXMPTIONCODE", length = 6)
	public String getCtiexmptioncode() {
		return this.ctiexmptioncode;
	}

	public void setCtiexmptioncode(String ctiexmptioncode) {
		this.ctiexmptioncode = ctiexmptioncode;
	}

	@Column(name = "CTIBUYRSELLBPID", length = 15)
	public String getCtibuyrsellbpid() {
		return this.ctibuyrsellbpid;
	}

	public void setCtibuyrsellbpid(String ctibuyrsellbpid) {
		this.ctibuyrsellbpid = ctibuyrsellbpid;
	}

	@Column(name = "CTICPRTYBPID", length = 15)
	public String getCticprtybpid() {
		return this.cticprtybpid;
	}

	public void setCticprtybpid(String cticprtybpid) {
		this.cticprtybpid = cticprtybpid;
	}

	@Column(name = "CTILCLBRKRCUR", length = 3)
	public String getCtilclbrkrcur() {
		return this.ctilclbrkrcur;
	}

	public void setCtilclbrkrcur(String ctilclbrkrcur) {
		this.ctilclbrkrcur = ctilclbrkrcur;
	}

	@Column(name = "CTIACRDINTCUR", length = 3)
	public String getCtiacrdintcur() {
		return this.ctiacrdintcur;
	}

	public void setCtiacrdintcur(String ctiacrdintcur) {
		this.ctiacrdintcur = ctiacrdintcur;
	}

	@Column(name = "CTIAUTHIND", precision = 3, scale = 0)
	public Short getCtiauthind() {
		return this.ctiauthind;
	}

	public void setCtiauthind(Short ctiauthind) {
		this.ctiauthind = ctiauthind;
	}

	@Column(name = "CTIORDRID", precision = 9, scale = 0)
	public Integer getCtiordrid() {
		return this.ctiordrid;
	}

	public void setCtiordrid(Integer ctiordrid) {
		this.ctiordrid = ctiordrid;
	}

	@Column(name = "MC_DELETE_TS", length = 13)
	public Date getMcDeleteTs() {
		return this.mcDeleteTs;
	}

	public void setMcDeleteTs(Date mcDeleteTs) {
		this.mcDeleteTs = mcDeleteTs;
	}

	@Column(name = "DS_CUSTODY_TI_STAGING_VER", precision = 4, scale = 0)
	public Short getDsCustodyTiStagingVer() {
		return this.dsCustodyTiStagingVer;
	}

	public void setDsCustodyTiStagingVer(Short dsCustodyTiStagingVer) {
		this.dsCustodyTiStagingVer = dsCustodyTiStagingVer;
	}

	@Column(name = "DM_LSTUPDDT", length = 13)
	public Date getDmLstupddt() {
		return this.dmLstupddt;
	}

	public void setDmLstupddt(Date dmLstupddt) {
		this.dmLstupddt = dmLstupddt;
	}

	@Column(name = "CTIPSTBPID", length = 15)
	public String getCtipstbpid() {
		return this.ctipstbpid;
	}

	public void setCtipstbpid(String ctipstbpid) {
		this.ctipstbpid = ctipstbpid;
	}

	@Column(name = "CTITRANSTYPE", length = 4)
	public String getCtitranstype() {
		return this.ctitranstype;
	}

	public void setCtitranstype(String ctitranstype) {
		this.ctitranstype = ctitranstype;
	}

	@Column(name = "CTISTTPAYABLE", precision = 31, scale = 15)
	public BigDecimal getCtisttpayable() {
		return this.ctisttpayable;
	}

	public void setCtisttpayable(BigDecimal ctisttpayable) {
		this.ctisttpayable = ctisttpayable;
	}

	@Column(name = "CTI_ERROR_MESSAGE", length = 4000)
	public String getCtiErrorMessage() {
		return this.ctiErrorMessage;
	}

	public void setCtiErrorMessage(String ctiErrorMessage) {
		this.ctiErrorMessage = ctiErrorMessage;
	}

	@Column(name = "CTIIPO_IND", length = 1)
	public String getCtiipoInd() {
		return this.ctiipoInd;
	}

	public void setCtiipoInd(String ctiipoInd) {
		this.ctiipoInd = ctiipoInd;
	}

	@Column(name = "CTIPLREF", length = 35)
	public String getCtiplref() {
		return this.ctiplref;
	}

	public void setCtiplref(String ctiplref) {
		this.ctiplref = ctiplref;
	}

	@Column(name = "DM_BTNUMERIC", precision = 10, scale = 0)
	public Long getDmBtnumeric() {
		return this.dmBtnumeric;
	}

	public void setDmBtnumeric(Long dmBtnumeric) {
		this.dmBtnumeric = dmBtnumeric;
	}

	@Column(name = "DM_BTID", precision = 5, scale = 0)
	public Integer getDmBtid() {
		return this.dmBtid;
	}

	public void setDmBtid(Integer dmBtid) {
		this.dmBtid = dmBtid;
	}

	@Column(name = "DM_USERID", precision = 8, scale = 0)
	public Integer getDmUserid() {
		return this.dmUserid;
	}

	public void setDmUserid(Integer dmUserid) {
		this.dmUserid = dmUserid;
	}

	@Column(name = "DM_WSID", precision = 4, scale = 0)
	public Short getDmWsid() {
		return this.dmWsid;
	}

	public void setDmWsid(Short dmWsid) {
		this.dmWsid = dmWsid;
	}

	@Column(name = "CTIBYRSLLRBIC", length = 12)
	public String getCtibyrsllrbic() {
		return this.ctibyrsllrbic;
	}

	public void setCtibyrsllrbic(String ctibyrsllrbic) {
		this.ctibyrsllrbic = ctibyrsllrbic;
	}

	@Column(name = "BUYERSELLERTYPE", length = 2)
	public String getBuyersellertype() {
		return this.buyersellertype;
	}

	public void setBuyersellertype(String buyersellertype) {
		this.buyersellertype = buyersellertype;
	}

	@Column(name = "COUNTERPARTYTYPE", length = 2)
	public String getCounterpartytype() {
		return this.counterpartytype;
	}

	public void setCounterpartytype(String counterpartytype) {
		this.counterpartytype = counterpartytype;
	}

	@Column(name = "CTICPRTYBIC", length = 12)
	public String getCticprtybic() {
		return this.cticprtybic;
	}

	public void setCticprtybic(String cticprtybic) {
		this.cticprtybic = cticprtybic;
	}

	@Column(name = "CTIRCVDLVCSTDNACC", length = 35)
	public String getCtircvdlvcstdnacc() {
		return this.ctircvdlvcstdnacc;
	}

	public void setCtircvdlvcstdnacc(String ctircvdlvcstdnacc) {
		this.ctircvdlvcstdnacc = ctircvdlvcstdnacc;
	}

	@Column(name = "CTIAGNTACCINST", length = 35)
	public String getCtiagntaccinst() {
		return this.ctiagntaccinst;
	}

	public void setCtiagntaccinst(String ctiagntaccinst) {
		this.ctiagntaccinst = ctiagntaccinst;
	}

	@Column(name = "CTIBYRSLLRACC", length = 35)
	public String getCtibyrsllracc() {
		return this.ctibyrsllracc;
	}

	public void setCtibyrsllracc(String ctibyrsllracc) {
		this.ctibyrsllracc = ctibyrsllracc;
	}

	@Column(name = "CTIPSETTYPE", length = 2)
	public String getCtipsettype() {
		return this.ctipsettype;
	}

	public void setCtipsettype(String ctipsettype) {
		this.ctipsettype = ctipsettype;
	}

	@Column(name = "CTIPSETBIC", length = 14)
	public String getCtipsetbic() {
		return this.ctipsetbic;
	}

	public void setCtipsetbic(String ctipsetbic) {
		this.ctipsetbic = ctipsetbic;
	}

	@Column(name = "CTIAGENTTYPE", length = 2)
	public String getCtiagenttype() {
		return this.ctiagenttype;
	}

	public void setCtiagenttype(String ctiagenttype) {
		this.ctiagenttype = ctiagenttype;
	}

	@Column(name = "CTIAGENTBIC", length = 14)
	public String getCtiagentbic() {
		return this.ctiagentbic;
	}

	public void setCtiagentbic(String ctiagentbic) {
		this.ctiagentbic = ctiagentbic;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DsCustodyTiStagingId))
			return false;
		DsCustodyTiStagingId castOther = (DsCustodyTiStagingId) other;

		return ((this.getCtitransrefnum() == castOther.getCtitransrefnum())
				|| (this.getCtitransrefnum() != null && castOther.getCtitransrefnum() != null
						&& this.getCtitransrefnum().equals(castOther.getCtitransrefnum())))
				&& ((this.getCtistatusmesg() == castOther.getCtistatusmesg())
						|| (this.getCtistatusmesg() != null && castOther.getCtistatusmesg() != null
								&& this.getCtistatusmesg().equals(castOther.getCtistatusmesg())))
				&& ((this.getCtigroupid() == castOther.getCtigroupid()) || (this.getCtigroupid() != null
						&& castOther.getCtigroupid() != null && this.getCtigroupid().equals(castOther.getCtigroupid())))
				&& ((this.getCtiuserid() == castOther.getCtiuserid()) || (this.getCtiuserid() != null
						&& castOther.getCtiuserid() != null && this.getCtiuserid().equals(castOther.getCtiuserid())))
				&& ((this.getCtimessagetype() == castOther.getCtimessagetype())
						|| (this.getCtimessagetype() != null && castOther.getCtimessagetype() != null
								&& this.getCtimessagetype().equals(castOther.getCtimessagetype())))
				&& ((this.getCtifreeformat() == castOther.getCtifreeformat())
						|| (this.getCtifreeformat() != null && castOther.getCtifreeformat() != null
								&& this.getCtifreeformat().equals(castOther.getCtifreeformat())))
				&& ((this.getCtiprepdate() == castOther.getCtiprepdate())
						|| (this.getCtiprepdate() != null && castOther.getCtiprepdate() != null
								&& this.getCtiprepdate().equals(castOther.getCtiprepdate())))
				&& ((this.getCtitradedate() == castOther.getCtitradedate())
						|| (this.getCtitradedate() != null && castOther.getCtitradedate() != null
								&& this.getCtitradedate().equals(castOther.getCtitradedate())))
				&& ((this.getCtivaluedate() == castOther.getCtivaluedate())
						|| (this.getCtivaluedate() != null && castOther.getCtivaluedate() != null
								&& this.getCtivaluedate().equals(castOther.getCtivaluedate())))
				&& ((this.getCtidealcurr() == castOther.getCtidealcurr())
						|| (this.getCtidealcurr() != null && castOther.getCtidealcurr() != null
								&& this.getCtidealcurr().equals(castOther.getCtidealcurr())))
				&& ((this.getCtidealprice() == castOther.getCtidealprice())
						|| (this.getCtidealprice() != null && castOther.getCtidealprice() != null
								&& this.getCtidealprice().equals(castOther.getCtidealprice())))
				&& ((this.getCtisecurityname() == castOther.getCtisecurityname())
						|| (this.getCtisecurityname() != null && castOther.getCtisecurityname() != null
								&& this.getCtisecurityname().equals(castOther.getCtisecurityname())))
				&& ((this.getCtisecnum() == castOther.getCtisecnum()) || (this.getCtisecnum() != null
						&& castOther.getCtisecnum() != null && this.getCtisecnum().equals(castOther.getCtisecnum())))
				&& ((this.getCtinumscheme() == castOther.getCtinumscheme())
						|| (this.getCtinumscheme() != null && castOther.getCtinumscheme() != null
								&& this.getCtinumscheme().equals(castOther.getCtinumscheme())))
				&& ((this.getCtiqtysecurities() == castOther.getCtiqtysecurities())
						|| (this.getCtiqtysecurities() != null && castOther.getCtiqtysecurities() != null
								&& this.getCtiqtysecurities().equals(castOther.getCtiqtysecurities())))
				&& ((this.getCtiscaid() == castOther.getCtiscaid()) || (this.getCtiscaid() != null
						&& castOther.getCtiscaid() != null && this.getCtiscaid().equals(castOther.getCtiscaid())))
				&& ((this.getCticashacc() == castOther.getCticashacc()) || (this.getCticashacc() != null
						&& castOther.getCticashacc() != null && this.getCticashacc().equals(castOther.getCticashacc())))
				&& ((this.getCticustodian() == castOther.getCticustodian())
						|| (this.getCticustodian() != null && castOther.getCticustodian() != null
								&& this.getCticustodian().equals(castOther.getCticustodian())))
				&& ((this.getCtiglobalcustodian() == castOther.getCtiglobalcustodian())
						|| (this.getCtiglobalcustodian() != null && castOther.getCtiglobalcustodian() != null
								&& this.getCtiglobalcustodian().equals(castOther.getCtiglobalcustodian())))
				&& ((this.getCtibuyer() == castOther.getCtibuyer()) || (this.getCtibuyer() != null
						&& castOther.getCtibuyer() != null && this.getCtibuyer().equals(castOther.getCtibuyer())))
				&& ((this.getCtiseller() == castOther.getCtiseller()) || (this.getCtiseller() != null
						&& castOther.getCtiseller() != null && this.getCtiseller().equals(castOther.getCtiseller())))
				&& ((this.getCtibeneficiary() == castOther.getCtibeneficiary())
						|| (this.getCtibeneficiary() != null && castOther.getCtibeneficiary() != null
								&& this.getCtibeneficiary().equals(castOther.getCtibeneficiary())))
				&& ((this.getCtisttlmntcurr() == castOther.getCtisttlmntcurr())
						|| (this.getCtisttlmntcurr() != null && castOther.getCtisttlmntcurr() != null
								&& this.getCtisttlmntcurr().equals(castOther.getCtisttlmntcurr())))
				&& ((this.getCtisttlmnttype() == castOther.getCtisttlmnttype())
						|| (this.getCtisttlmnttype() != null && castOther.getCtisttlmnttype() != null
								&& this.getCtisttlmnttype().equals(castOther.getCtisttlmnttype())))
				&& ((this.getCtisttlmntamount() == castOther.getCtisttlmntamount())
						|| (this.getCtisttlmntamount() != null && castOther.getCtisttlmntamount() != null
								&& this.getCtisttlmntamount().equals(castOther.getCtisttlmntamount())))
				&& ((this.getCtiplacetrade() == castOther.getCtiplacetrade())
						|| (this.getCtiplacetrade() != null && castOther.getCtiplacetrade() != null
								&& this.getCtiplacetrade().equals(castOther.getCtiplacetrade())))
				&& ((this.getCticustomerreference() == castOther.getCticustomerreference())
						|| (this.getCticustomerreference() != null && castOther.getCticustomerreference() != null
								&& this.getCticustomerreference().equals(castOther.getCticustomerreference())))
				&& ((this.getCticompany() == castOther.getCticompany()) || (this.getCticompany() != null
						&& castOther.getCticompany() != null && this.getCticompany().equals(castOther.getCticompany())))
				&& ((this.getCtiaccountcentre() == castOther.getCtiaccountcentre())
						|| (this.getCtiaccountcentre() != null && castOther.getCtiaccountcentre() != null
								&& this.getCtiaccountcentre().equals(castOther.getCtiaccountcentre())))
				&& ((this.getCtioldtransrefnum() == castOther.getCtioldtransrefnum())
						|| (this.getCtioldtransrefnum() != null && castOther.getCtioldtransrefnum() != null
								&& this.getCtioldtransrefnum().equals(castOther.getCtioldtransrefnum())))
				&& ((this.getCtilastupdateddate() == castOther.getCtilastupdateddate())
						|| (this.getCtilastupdateddate() != null && castOther.getCtilastupdateddate() != null
								&& this.getCtilastupdateddate().equals(castOther.getCtilastupdateddate())))
				&& ((this.getCtifunctionofmessage() == castOther.getCtifunctionofmessage())
						|| (this.getCtifunctionofmessage() != null && castOther.getCtifunctionofmessage() != null
								&& this.getCtifunctionofmessage().equals(castOther.getCtifunctionofmessage())))
				&& ((this.getCticreatedby() == castOther.getCticreatedby())
						|| (this.getCticreatedby() != null && castOther.getCticreatedby() != null
								&& this.getCticreatedby().equals(castOther.getCticreatedby())))
				&& ((this.getCtlastupdatedby() == castOther.getCtlastupdatedby())
						|| (this.getCtlastupdatedby() != null && castOther.getCtlastupdatedby() != null
								&& this.getCtlastupdatedby().equals(castOther.getCtlastupdatedby())))
				&& ((this.getCtiseclongnm1() == castOther.getCtiseclongnm1())
						|| (this.getCtiseclongnm1() != null && castOther.getCtiseclongnm1() != null
								&& this.getCtiseclongnm1().equals(castOther.getCtiseclongnm1())))
				&& ((this.getCtiseclongnm2() == castOther.getCtiseclongnm2())
						|| (this.getCtiseclongnm2() != null && castOther.getCtiseclongnm2() != null
								&& this.getCtiseclongnm2().equals(castOther.getCtiseclongnm2())))
				&& ((this.getCtiseclongnm3() == castOther.getCtiseclongnm3())
						|| (this.getCtiseclongnm3() != null && castOther.getCtiseclongnm3() != null
								&& this.getCtiseclongnm3().equals(castOther.getCtiseclongnm3())))
				&& ((this.getCtiseclongnm4() == castOther.getCtiseclongnm4())
						|| (this.getCtiseclongnm4() != null && castOther.getCtiseclongnm4() != null
								&& this.getCtiseclongnm4().equals(castOther.getCtiseclongnm4())))
				&& ((this.getCtibuyerflg() == castOther.getCtibuyerflg())
						|| (this.getCtibuyerflg() != null && castOther.getCtibuyerflg() != null
								&& this.getCtibuyerflg().equals(castOther.getCtibuyerflg())))
				&& ((this.getCtisellerflg() == castOther.getCtisellerflg())
						|| (this.getCtisellerflg() != null && castOther.getCtisellerflg() != null
								&& this.getCtisellerflg().equals(castOther.getCtisellerflg())))
				&& ((this.getCtichargeacc() == castOther.getCtichargeacc())
						|| (this.getCtichargeacc() != null && castOther.getCtichargeacc() != null
								&& this.getCtichargeacc().equals(castOther.getCtichargeacc())))
				&& ((this.getBfsfilereferenceno() == castOther.getBfsfilereferenceno())
						|| (this.getBfsfilereferenceno() != null && castOther.getBfsfilereferenceno() != null
								&& this.getBfsfilereferenceno().equals(castOther.getBfsfilereferenceno())))
				&& ((this.getCtiauthby() == castOther.getCtiauthby()) || (this.getCtiauthby() != null
						&& castOther.getCtiauthby() != null && this.getCtiauthby().equals(castOther.getCtiauthby())))
				&& ((this.getClientname() == castOther.getClientname()) || (this.getClientname() != null
						&& castOther.getClientname() != null && this.getClientname().equals(castOther.getClientname())))
				&& ((this.getCtirecdelagntname() == castOther.getCtirecdelagntname())
						|| (this.getCtirecdelagntname() != null && castOther.getCtirecdelagntname() != null
								&& this.getCtirecdelagntname().equals(castOther.getCtirecdelagntname())))
				&& ((this.getCticlient() == castOther.getCticlient()) || (this.getCticlient() != null
						&& castOther.getCticlient() != null && this.getCticlient().equals(castOther.getCticlient())))
				&& ((this.getCtiTranRefNum() == castOther.getCtiTranRefNum())
						|| (this.getCtiTranRefNum() != null && castOther.getCtiTranRefNum() != null
								&& this.getCtiTranRefNum().equals(castOther.getCtiTranRefNum())))
				&& ((this.getCtiagent() == castOther.getCtiagent()) || (this.getCtiagent() != null
						&& castOther.getCtiagent() != null && this.getCtiagent().equals(castOther.getCtiagent())))
				&& ((this.getCtidealamount() == castOther.getCtidealamount())
						|| (this.getCtidealamount() != null && castOther.getCtidealamount() != null
								&& this.getCtidealamount().equals(castOther.getCtidealamount())))
				&& ((this.getCtiupldfilename() == castOther.getCtiupldfilename())
						|| (this.getCtiupldfilename() != null && castOther.getCtiupldfilename() != null
								&& this.getCtiupldfilename().equals(castOther.getCtiupldfilename())))
				&& ((this.getVersionnum() == castOther.getVersionnum()) || (this.getVersionnum() != null
						&& castOther.getVersionnum() != null && this.getVersionnum().equals(castOther.getVersionnum())))
				&& ((this.getSecidenscheme() == castOther.getSecidenscheme())
						|| (this.getSecidenscheme() != null && castOther.getSecidenscheme() != null
								&& this.getSecidenscheme().equals(castOther.getSecidenscheme())))
				&& ((this.getCticlienttype() == castOther.getCticlienttype())
						|| (this.getCticlienttype() != null && castOther.getCticlienttype() != null
								&& this.getCticlienttype().equals(castOther.getCticlienttype())))
				&& ((this.getCtilclbrkramt() == castOther.getCtilclbrkramt())
						|| (this.getCtilclbrkramt() != null && castOther.getCtilclbrkramt() != null
								&& this.getCtilclbrkramt().equals(castOther.getCtilclbrkramt())))
				&& ((this.getCtiacrdintamt() == castOther.getCtiacrdintamt())
						|| (this.getCtiacrdintamt() != null && castOther.getCtiacrdintamt() != null
								&& this.getCtiacrdintamt().equals(castOther.getCtiacrdintamt())))
				&& ((this.getCtisttpybind() == castOther.getCtisttpybind())
						|| (this.getCtisttpybind() != null && castOther.getCtisttpybind() != null
								&& this.getCtisttpybind().equals(castOther.getCtisttpybind())))
				&& ((this.getCticoboind() == castOther.getCticoboind()) || (this.getCticoboind() != null
						&& castOther.getCticoboind() != null && this.getCticoboind().equals(castOther.getCticoboind())))
				&& ((this.getCtiexmptioncode() == castOther.getCtiexmptioncode())
						|| (this.getCtiexmptioncode() != null && castOther.getCtiexmptioncode() != null
								&& this.getCtiexmptioncode().equals(castOther.getCtiexmptioncode())))
				&& ((this.getCtibuyrsellbpid() == castOther.getCtibuyrsellbpid())
						|| (this.getCtibuyrsellbpid() != null && castOther.getCtibuyrsellbpid() != null
								&& this.getCtibuyrsellbpid().equals(castOther.getCtibuyrsellbpid())))
				&& ((this.getCticprtybpid() == castOther.getCticprtybpid())
						|| (this.getCticprtybpid() != null && castOther.getCticprtybpid() != null
								&& this.getCticprtybpid().equals(castOther.getCticprtybpid())))
				&& ((this.getCtilclbrkrcur() == castOther.getCtilclbrkrcur())
						|| (this.getCtilclbrkrcur() != null && castOther.getCtilclbrkrcur() != null
								&& this.getCtilclbrkrcur().equals(castOther.getCtilclbrkrcur())))
				&& ((this.getCtiacrdintcur() == castOther.getCtiacrdintcur())
						|| (this.getCtiacrdintcur() != null && castOther.getCtiacrdintcur() != null
								&& this.getCtiacrdintcur().equals(castOther.getCtiacrdintcur())))
				&& ((this.getCtiauthind() == castOther.getCtiauthind()) || (this.getCtiauthind() != null
						&& castOther.getCtiauthind() != null && this.getCtiauthind().equals(castOther.getCtiauthind())))
				&& ((this.getCtiordrid() == castOther.getCtiordrid()) || (this.getCtiordrid() != null
						&& castOther.getCtiordrid() != null && this.getCtiordrid().equals(castOther.getCtiordrid())))
				&& ((this.getMcDeleteTs() == castOther.getMcDeleteTs()) || (this.getMcDeleteTs() != null
						&& castOther.getMcDeleteTs() != null && this.getMcDeleteTs().equals(castOther.getMcDeleteTs())))
				&& ((this.getDsCustodyTiStagingVer() == castOther.getDsCustodyTiStagingVer())
						|| (this.getDsCustodyTiStagingVer() != null && castOther.getDsCustodyTiStagingVer() != null
								&& this.getDsCustodyTiStagingVer().equals(castOther.getDsCustodyTiStagingVer())))
				&& ((this.getDmLstupddt() == castOther.getDmLstupddt()) || (this.getDmLstupddt() != null
						&& castOther.getDmLstupddt() != null && this.getDmLstupddt().equals(castOther.getDmLstupddt())))
				&& ((this.getCtipstbpid() == castOther.getCtipstbpid()) || (this.getCtipstbpid() != null
						&& castOther.getCtipstbpid() != null && this.getCtipstbpid().equals(castOther.getCtipstbpid())))
				&& ((this.getCtitranstype() == castOther.getCtitranstype())
						|| (this.getCtitranstype() != null && castOther.getCtitranstype() != null
								&& this.getCtitranstype().equals(castOther.getCtitranstype())))
				&& ((this.getCtisttpayable() == castOther.getCtisttpayable())
						|| (this.getCtisttpayable() != null && castOther.getCtisttpayable() != null
								&& this.getCtisttpayable().equals(castOther.getCtisttpayable())))
				&& ((this.getCtiErrorMessage() == castOther.getCtiErrorMessage())
						|| (this.getCtiErrorMessage() != null && castOther.getCtiErrorMessage() != null
								&& this.getCtiErrorMessage().equals(castOther.getCtiErrorMessage())))
				&& ((this.getCtiipoInd() == castOther.getCtiipoInd()) || (this.getCtiipoInd() != null
						&& castOther.getCtiipoInd() != null && this.getCtiipoInd().equals(castOther.getCtiipoInd())))
				&& ((this.getCtiplref() == castOther.getCtiplref()) || (this.getCtiplref() != null
						&& castOther.getCtiplref() != null && this.getCtiplref().equals(castOther.getCtiplref())))
				&& ((this.getDmBtnumeric() == castOther.getDmBtnumeric())
						|| (this.getDmBtnumeric() != null && castOther.getDmBtnumeric() != null
								&& this.getDmBtnumeric().equals(castOther.getDmBtnumeric())))
				&& ((this.getDmBtid() == castOther.getDmBtid()) || (this.getDmBtid() != null
						&& castOther.getDmBtid() != null && this.getDmBtid().equals(castOther.getDmBtid())))
				&& ((this.getDmUserid() == castOther.getDmUserid()) || (this.getDmUserid() != null
						&& castOther.getDmUserid() != null && this.getDmUserid().equals(castOther.getDmUserid())))
				&& ((this.getDmWsid() == castOther.getDmWsid()) || (this.getDmWsid() != null
						&& castOther.getDmWsid() != null && this.getDmWsid().equals(castOther.getDmWsid())))
				&& ((this.getCtibyrsllrbic() == castOther.getCtibyrsllrbic())
						|| (this.getCtibyrsllrbic() != null && castOther.getCtibyrsllrbic() != null
								&& this.getCtibyrsllrbic().equals(castOther.getCtibyrsllrbic())))
				&& ((this.getBuyersellertype() == castOther.getBuyersellertype())
						|| (this.getBuyersellertype() != null && castOther.getBuyersellertype() != null
								&& this.getBuyersellertype().equals(castOther.getBuyersellertype())))
				&& ((this.getCounterpartytype() == castOther.getCounterpartytype())
						|| (this.getCounterpartytype() != null && castOther.getCounterpartytype() != null
								&& this.getCounterpartytype().equals(castOther.getCounterpartytype())))
				&& ((this.getCticprtybic() == castOther.getCticprtybic())
						|| (this.getCticprtybic() != null && castOther.getCticprtybic() != null
								&& this.getCticprtybic().equals(castOther.getCticprtybic())))
				&& ((this.getCtircvdlvcstdnacc() == castOther.getCtircvdlvcstdnacc())
						|| (this.getCtircvdlvcstdnacc() != null && castOther.getCtircvdlvcstdnacc() != null
								&& this.getCtircvdlvcstdnacc().equals(castOther.getCtircvdlvcstdnacc())))
				&& ((this.getCtiagntaccinst() == castOther.getCtiagntaccinst())
						|| (this.getCtiagntaccinst() != null && castOther.getCtiagntaccinst() != null
								&& this.getCtiagntaccinst().equals(castOther.getCtiagntaccinst())))
				&& ((this.getCtibyrsllracc() == castOther.getCtibyrsllracc())
						|| (this.getCtibyrsllracc() != null && castOther.getCtibyrsllracc() != null
								&& this.getCtibyrsllracc().equals(castOther.getCtibyrsllracc())))
				&& ((this.getCtipsettype() == castOther.getCtipsettype())
						|| (this.getCtipsettype() != null && castOther.getCtipsettype() != null
								&& this.getCtipsettype().equals(castOther.getCtipsettype())))
				&& ((this.getCtipsetbic() == castOther.getCtipsetbic()) || (this.getCtipsetbic() != null
						&& castOther.getCtipsetbic() != null && this.getCtipsetbic().equals(castOther.getCtipsetbic())))
				&& ((this.getCtiagenttype() == castOther.getCtiagenttype())
						|| (this.getCtiagenttype() != null && castOther.getCtiagenttype() != null
								&& this.getCtiagenttype().equals(castOther.getCtiagenttype())))
				&& ((this.getCtiagentbic() == castOther.getCtiagentbic())
						|| (this.getCtiagentbic() != null && castOther.getCtiagentbic() != null
								&& this.getCtiagentbic().equals(castOther.getCtiagentbic())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtitransrefnum() == null ? 0 : this.getCtitransrefnum().hashCode());
		result = 37 * result + (getCtistatusmesg() == null ? 0 : this.getCtistatusmesg().hashCode());
		result = 37 * result + (getCtigroupid() == null ? 0 : this.getCtigroupid().hashCode());
		result = 37 * result + (getCtiuserid() == null ? 0 : this.getCtiuserid().hashCode());
		result = 37 * result + (getCtimessagetype() == null ? 0 : this.getCtimessagetype().hashCode());
		result = 37 * result + (getCtifreeformat() == null ? 0 : this.getCtifreeformat().hashCode());
		result = 37 * result + (getCtiprepdate() == null ? 0 : this.getCtiprepdate().hashCode());
		result = 37 * result + (getCtitradedate() == null ? 0 : this.getCtitradedate().hashCode());
		result = 37 * result + (getCtivaluedate() == null ? 0 : this.getCtivaluedate().hashCode());
		result = 37 * result + (getCtidealcurr() == null ? 0 : this.getCtidealcurr().hashCode());
		result = 37 * result + (getCtidealprice() == null ? 0 : this.getCtidealprice().hashCode());
		result = 37 * result + (getCtisecurityname() == null ? 0 : this.getCtisecurityname().hashCode());
		result = 37 * result + (getCtisecnum() == null ? 0 : this.getCtisecnum().hashCode());
		result = 37 * result + (getCtinumscheme() == null ? 0 : this.getCtinumscheme().hashCode());
		result = 37 * result + (getCtiqtysecurities() == null ? 0 : this.getCtiqtysecurities().hashCode());
		result = 37 * result + (getCtiscaid() == null ? 0 : this.getCtiscaid().hashCode());
		result = 37 * result + (getCticashacc() == null ? 0 : this.getCticashacc().hashCode());
		result = 37 * result + (getCticustodian() == null ? 0 : this.getCticustodian().hashCode());
		result = 37 * result + (getCtiglobalcustodian() == null ? 0 : this.getCtiglobalcustodian().hashCode());
		result = 37 * result + (getCtibuyer() == null ? 0 : this.getCtibuyer().hashCode());
		result = 37 * result + (getCtiseller() == null ? 0 : this.getCtiseller().hashCode());
		result = 37 * result + (getCtibeneficiary() == null ? 0 : this.getCtibeneficiary().hashCode());
		result = 37 * result + (getCtisttlmntcurr() == null ? 0 : this.getCtisttlmntcurr().hashCode());
		result = 37 * result + (getCtisttlmnttype() == null ? 0 : this.getCtisttlmnttype().hashCode());
		result = 37 * result + (getCtisttlmntamount() == null ? 0 : this.getCtisttlmntamount().hashCode());
		result = 37 * result + (getCtiplacetrade() == null ? 0 : this.getCtiplacetrade().hashCode());
		result = 37 * result + (getCticustomerreference() == null ? 0 : this.getCticustomerreference().hashCode());
		result = 37 * result + (getCticompany() == null ? 0 : this.getCticompany().hashCode());
		result = 37 * result + (getCtiaccountcentre() == null ? 0 : this.getCtiaccountcentre().hashCode());
		result = 37 * result + (getCtioldtransrefnum() == null ? 0 : this.getCtioldtransrefnum().hashCode());
		result = 37 * result + (getCtilastupdateddate() == null ? 0 : this.getCtilastupdateddate().hashCode());
		result = 37 * result + (getCtifunctionofmessage() == null ? 0 : this.getCtifunctionofmessage().hashCode());
		result = 37 * result + (getCticreatedby() == null ? 0 : this.getCticreatedby().hashCode());
		result = 37 * result + (getCtlastupdatedby() == null ? 0 : this.getCtlastupdatedby().hashCode());
		result = 37 * result + (getCtiseclongnm1() == null ? 0 : this.getCtiseclongnm1().hashCode());
		result = 37 * result + (getCtiseclongnm2() == null ? 0 : this.getCtiseclongnm2().hashCode());
		result = 37 * result + (getCtiseclongnm3() == null ? 0 : this.getCtiseclongnm3().hashCode());
		result = 37 * result + (getCtiseclongnm4() == null ? 0 : this.getCtiseclongnm4().hashCode());
		result = 37 * result + (getCtibuyerflg() == null ? 0 : this.getCtibuyerflg().hashCode());
		result = 37 * result + (getCtisellerflg() == null ? 0 : this.getCtisellerflg().hashCode());
		result = 37 * result + (getCtichargeacc() == null ? 0 : this.getCtichargeacc().hashCode());
		result = 37 * result + (getBfsfilereferenceno() == null ? 0 : this.getBfsfilereferenceno().hashCode());
		result = 37 * result + (getCtiauthby() == null ? 0 : this.getCtiauthby().hashCode());
		result = 37 * result + (getClientname() == null ? 0 : this.getClientname().hashCode());
		result = 37 * result + (getCtirecdelagntname() == null ? 0 : this.getCtirecdelagntname().hashCode());
		result = 37 * result + (getCticlient() == null ? 0 : this.getCticlient().hashCode());
		result = 37 * result + (getCtiTranRefNum() == null ? 0 : this.getCtiTranRefNum().hashCode());
		result = 37 * result + (getCtiagent() == null ? 0 : this.getCtiagent().hashCode());
		result = 37 * result + (getCtidealamount() == null ? 0 : this.getCtidealamount().hashCode());
		result = 37 * result + (getCtiupldfilename() == null ? 0 : this.getCtiupldfilename().hashCode());
		result = 37 * result + (getVersionnum() == null ? 0 : this.getVersionnum().hashCode());
		result = 37 * result + (getSecidenscheme() == null ? 0 : this.getSecidenscheme().hashCode());
		result = 37 * result + (getCticlienttype() == null ? 0 : this.getCticlienttype().hashCode());
		result = 37 * result + (getCtilclbrkramt() == null ? 0 : this.getCtilclbrkramt().hashCode());
		result = 37 * result + (getCtiacrdintamt() == null ? 0 : this.getCtiacrdintamt().hashCode());
		result = 37 * result + (getCtisttpybind() == null ? 0 : this.getCtisttpybind().hashCode());
		result = 37 * result + (getCticoboind() == null ? 0 : this.getCticoboind().hashCode());
		result = 37 * result + (getCtiexmptioncode() == null ? 0 : this.getCtiexmptioncode().hashCode());
		result = 37 * result + (getCtibuyrsellbpid() == null ? 0 : this.getCtibuyrsellbpid().hashCode());
		result = 37 * result + (getCticprtybpid() == null ? 0 : this.getCticprtybpid().hashCode());
		result = 37 * result + (getCtilclbrkrcur() == null ? 0 : this.getCtilclbrkrcur().hashCode());
		result = 37 * result + (getCtiacrdintcur() == null ? 0 : this.getCtiacrdintcur().hashCode());
		result = 37 * result + (getCtiauthind() == null ? 0 : this.getCtiauthind().hashCode());
		result = 37 * result + (getCtiordrid() == null ? 0 : this.getCtiordrid().hashCode());
		result = 37 * result + (getMcDeleteTs() == null ? 0 : this.getMcDeleteTs().hashCode());
		result = 37 * result + (getDsCustodyTiStagingVer() == null ? 0 : this.getDsCustodyTiStagingVer().hashCode());
		result = 37 * result + (getDmLstupddt() == null ? 0 : this.getDmLstupddt().hashCode());
		result = 37 * result + (getCtipstbpid() == null ? 0 : this.getCtipstbpid().hashCode());
		result = 37 * result + (getCtitranstype() == null ? 0 : this.getCtitranstype().hashCode());
		result = 37 * result + (getCtisttpayable() == null ? 0 : this.getCtisttpayable().hashCode());
		result = 37 * result + (getCtiErrorMessage() == null ? 0 : this.getCtiErrorMessage().hashCode());
		result = 37 * result + (getCtiipoInd() == null ? 0 : this.getCtiipoInd().hashCode());
		result = 37 * result + (getCtiplref() == null ? 0 : this.getCtiplref().hashCode());
		result = 37 * result + (getDmBtnumeric() == null ? 0 : this.getDmBtnumeric().hashCode());
		result = 37 * result + (getDmBtid() == null ? 0 : this.getDmBtid().hashCode());
		result = 37 * result + (getDmUserid() == null ? 0 : this.getDmUserid().hashCode());
		result = 37 * result + (getDmWsid() == null ? 0 : this.getDmWsid().hashCode());
		result = 37 * result + (getCtibyrsllrbic() == null ? 0 : this.getCtibyrsllrbic().hashCode());
		result = 37 * result + (getBuyersellertype() == null ? 0 : this.getBuyersellertype().hashCode());
		result = 37 * result + (getCounterpartytype() == null ? 0 : this.getCounterpartytype().hashCode());
		result = 37 * result + (getCticprtybic() == null ? 0 : this.getCticprtybic().hashCode());
		result = 37 * result + (getCtircvdlvcstdnacc() == null ? 0 : this.getCtircvdlvcstdnacc().hashCode());
		result = 37 * result + (getCtiagntaccinst() == null ? 0 : this.getCtiagntaccinst().hashCode());
		result = 37 * result + (getCtibyrsllracc() == null ? 0 : this.getCtibyrsllracc().hashCode());
		result = 37 * result + (getCtipsettype() == null ? 0 : this.getCtipsettype().hashCode());
		result = 37 * result + (getCtipsetbic() == null ? 0 : this.getCtipsetbic().hashCode());
		result = 37 * result + (getCtiagenttype() == null ? 0 : this.getCtiagenttype().hashCode());
		result = 37 * result + (getCtiagentbic() == null ? 0 : this.getCtiagentbic().hashCode());
		return result;
	}

}
