package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DsDomainsId generated by hbm2java
 */
@Embeddable
public class DsDomainsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 375537279909825206L;
	private String dmndomain;
	private String dmndomainval;
	private String dmndomaindesc;
	private String dmndomainvaldesc;
	private String createdby;
	private Date createddate;

	public DsDomainsId() {
	}

	public DsDomainsId(String dmndomain, String dmndomainval, String dmndomaindesc, String dmndomainvaldesc,
			String createdby, Date createddate) {
		this.dmndomain = dmndomain;
		this.dmndomainval = dmndomainval;
		this.dmndomaindesc = dmndomaindesc;
		this.dmndomainvaldesc = dmndomainvaldesc;
		this.createdby = createdby;
		this.createddate = createddate;
	}

	@Column(name = "dmndomain", length = 40)
	public String getDmndomain() {
		return this.dmndomain;
	}

	public void setDmndomain(String dmndomain) {
		this.dmndomain = dmndomain;
	}

	@Column(name = "dmndomainval", length = 40)
	public String getDmndomainval() {
		return this.dmndomainval;
	}

	public void setDmndomainval(String dmndomainval) {
		this.dmndomainval = dmndomainval;
	}

	@Column(name = "dmndomaindesc")
	public String getDmndomaindesc() {
		return this.dmndomaindesc;
	}

	public void setDmndomaindesc(String dmndomaindesc) {
		this.dmndomaindesc = dmndomaindesc;
	}

	@Column(name = "dmndomainvaldesc")
	public String getDmndomainvaldesc() {
		return this.dmndomainvaldesc;
	}

	public void setDmndomainvaldesc(String dmndomainvaldesc) {
		this.dmndomainvaldesc = dmndomainvaldesc;
	}

	@Column(name = "createdby", length = 101)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "createddate", length = 13)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DsDomainsId))
			return false;
		DsDomainsId castOther = (DsDomainsId) other;

		return ((this.getDmndomain() == castOther.getDmndomain()) || (this.getDmndomain() != null
				&& castOther.getDmndomain() != null && this.getDmndomain().equals(castOther.getDmndomain())))
				&& ((this.getDmndomainval() == castOther.getDmndomainval())
						|| (this.getDmndomainval() != null && castOther.getDmndomainval() != null
								&& this.getDmndomainval().equals(castOther.getDmndomainval())))
				&& ((this.getDmndomaindesc() == castOther.getDmndomaindesc())
						|| (this.getDmndomaindesc() != null && castOther.getDmndomaindesc() != null
								&& this.getDmndomaindesc().equals(castOther.getDmndomaindesc())))
				&& ((this.getDmndomainvaldesc() == castOther.getDmndomainvaldesc())
						|| (this.getDmndomainvaldesc() != null && castOther.getDmndomainvaldesc() != null
								&& this.getDmndomainvaldesc().equals(castOther.getDmndomainvaldesc())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this.getCreatedby() != null
						&& castOther.getCreatedby() != null && this.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateddate() == castOther.getCreateddate())
						|| (this.getCreateddate() != null && castOther.getCreateddate() != null
								&& this.getCreateddate().equals(castOther.getCreateddate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDmndomain() == null ? 0 : this.getDmndomain().hashCode());
		result = 37 * result + (getDmndomainval() == null ? 0 : this.getDmndomainval().hashCode());
		result = 37 * result + (getDmndomaindesc() == null ? 0 : this.getDmndomaindesc().hashCode());
		result = 37 * result + (getDmndomainvaldesc() == null ? 0 : this.getDmndomainvaldesc().hashCode());
		result = 37 * result + (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result + (getCreateddate() == null ? 0 : this.getCreateddate().hashCode());
		return result;
	}

}
