package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", schema = "public")
public class Person implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3749461752408816268L;
	private BigDecimal id;
	private String name;
	private String country;

	public Person() {
	}

	public Person(BigDecimal id) {
		this.id = id;
	}

	public Person(BigDecimal id, String name, String country) {
		this.id = id;
		this.name = name;
		this.country = country;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 20, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "country", length = 200)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
