package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReorderId generated by hbm2java
 */
@Embeddable
public class ReorderId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7389196189577370195L;
	private String reordercols;
	private String userid;
	private String tablename;
	private String screenname;
	private String state;

	public ReorderId() {
	}

	public ReorderId(String reordercols, String userid, String tablename, String screenname, String state) {
		this.reordercols = reordercols;
		this.userid = userid;
		this.tablename = tablename;
		this.screenname = screenname;
		this.state = state;
	}

	@Column(name = "reordercols", length = 400)
	public String getReordercols() {
		return this.reordercols;
	}

	public void setReordercols(String reordercols) {
		this.reordercols = reordercols;
	}

	@Column(name = "userid", length = 101)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "tablename", length = 50)
	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	@Column(name = "screenname", length = 50)
	public String getScreenname() {
		return this.screenname;
	}

	public void setScreenname(String screenname) {
		this.screenname = screenname;
	}

	@Column(name = "state", length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReorderId))
			return false;
		ReorderId castOther = (ReorderId) other;

		return ((this.getReordercols() == castOther.getReordercols()) || (this.getReordercols() != null
				&& castOther.getReordercols() != null && this.getReordercols().equals(castOther.getReordercols())))
				&& ((this.getUserid() == castOther.getUserid()) || (this.getUserid() != null
						&& castOther.getUserid() != null && this.getUserid().equals(castOther.getUserid())))
				&& ((this.getTablename() == castOther.getTablename()) || (this.getTablename() != null
						&& castOther.getTablename() != null && this.getTablename().equals(castOther.getTablename())))
				&& ((this.getScreenname() == castOther.getScreenname()) || (this.getScreenname() != null
						&& castOther.getScreenname() != null && this.getScreenname().equals(castOther.getScreenname())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null
						&& castOther.getState() != null && this.getState().equals(castOther.getState())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getReordercols() == null ? 0 : this.getReordercols().hashCode());
		result = 37 * result + (getUserid() == null ? 0 : this.getUserid().hashCode());
		result = 37 * result + (getTablename() == null ? 0 : this.getTablename().hashCode());
		result = 37 * result + (getScreenname() == null ? 0 : this.getScreenname().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		return result;
	}

}
