package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SearchTemplate generated by hbm2java
 */
@Entity
@Table(name = "search_template", schema = "public")
public class SearchTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8801275491368838979L;
	private SearchTemplateId id;

	public SearchTemplate() {
	}

	public SearchTemplate(SearchTemplateId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "tptuserid", column = @Column(name = "tptuserid", length = 101)),
			@AttributeOverride(name = "tptgroupid", column = @Column(name = "tptgroupid", length = 15)),
			@AttributeOverride(name = "tpttemplatename", column = @Column(name = "tpttemplatename", length = 50)),
			@AttributeOverride(name = "tpttemplate", column = @Column(name = "tpttemplate", length = 4000)),
			@AttributeOverride(name = "tptqltask", column = @Column(name = "tptqltask", length = 30)),
			@AttributeOverride(name = "tptscreentype", column = @Column(name = "tptscreentype", length = 1)),
			@AttributeOverride(name = "tptpublicflag", column = @Column(name = "tptpublicflag", length = 1)),
			@AttributeOverride(name = "tpttemplateobj", column = @Column(name = "tpttemplateobj")),
			@AttributeOverride(name = "tptfavourite", column = @Column(name = "tptfavourite", length = 10)),
			@AttributeOverride(name = "tptscreenstate", column = @Column(name = "tptscreenstate", length = 50)) })
	public SearchTemplateId getId() {
		return this.id;
	}

	public void setId(SearchTemplateId id) {
		this.id = id;
	}

}
