package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SearchTemplateId generated by hbm2java
 */
@Embeddable
public class SearchTemplateId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7758643453212166580L;
	private String tptuserid;
	private String tptgroupid;
	private String tpttemplatename;
	private String tpttemplate;
	private String tptqltask;
	private String tptscreentype;
	private String tptpublicflag;
	private String tpttemplateobj;
	private String tptfavourite;
	private String tptscreenstate;

	public SearchTemplateId() {
	}

	public SearchTemplateId(String tptuserid, String tptgroupid, String tpttemplatename, String tpttemplate,
			String tptqltask, String tptscreentype, String tptpublicflag, String tpttemplateobj, String tptfavourite,
			String tptscreenstate) {
		this.tptuserid = tptuserid;
		this.tptgroupid = tptgroupid;
		this.tpttemplatename = tpttemplatename;
		this.tpttemplate = tpttemplate;
		this.tptqltask = tptqltask;
		this.tptscreentype = tptscreentype;
		this.tptpublicflag = tptpublicflag;
		this.tpttemplateobj = tpttemplateobj;
		this.tptfavourite = tptfavourite;
		this.tptscreenstate = tptscreenstate;
	}

	@Column(name = "tptuserid", length = 101)
	public String getTptuserid() {
		return this.tptuserid;
	}

	public void setTptuserid(String tptuserid) {
		this.tptuserid = tptuserid;
	}

	@Column(name = "tptgroupid", length = 15)
	public String getTptgroupid() {
		return this.tptgroupid;
	}

	public void setTptgroupid(String tptgroupid) {
		this.tptgroupid = tptgroupid;
	}

	@Column(name = "tpttemplatename", length = 50)
	public String getTpttemplatename() {
		return this.tpttemplatename;
	}

	public void setTpttemplatename(String tpttemplatename) {
		this.tpttemplatename = tpttemplatename;
	}

	@Column(name = "tpttemplate", length = 4000)
	public String getTpttemplate() {
		return this.tpttemplate;
	}

	public void setTpttemplate(String tpttemplate) {
		this.tpttemplate = tpttemplate;
	}

	@Column(name = "tptqltask", length = 30)
	public String getTptqltask() {
		return this.tptqltask;
	}

	public void setTptqltask(String tptqltask) {
		this.tptqltask = tptqltask;
	}

	@Column(name = "tptscreentype", length = 1)
	public String getTptscreentype() {
		return this.tptscreentype;
	}

	public void setTptscreentype(String tptscreentype) {
		this.tptscreentype = tptscreentype;
	}

	@Column(name = "tptpublicflag", length = 1)
	public String getTptpublicflag() {
		return this.tptpublicflag;
	}

	public void setTptpublicflag(String tptpublicflag) {
		this.tptpublicflag = tptpublicflag;
	}

	@Column(name = "tpttemplateobj")
	public String getTpttemplateobj() {
		return this.tpttemplateobj;
	}

	public void setTpttemplateobj(String tpttemplateobj) {
		this.tpttemplateobj = tpttemplateobj;
	}

	@Column(name = "tptfavourite", length = 10)
	public String getTptfavourite() {
		return this.tptfavourite;
	}

	public void setTptfavourite(String tptfavourite) {
		this.tptfavourite = tptfavourite;
	}

	@Column(name = "tptscreenstate", length = 50)
	public String getTptscreenstate() {
		return this.tptscreenstate;
	}

	public void setTptscreenstate(String tptscreenstate) {
		this.tptscreenstate = tptscreenstate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SearchTemplateId))
			return false;
		SearchTemplateId castOther = (SearchTemplateId) other;

		return ((this.getTptuserid() == castOther.getTptuserid()) || (this.getTptuserid() != null
				&& castOther.getTptuserid() != null && this.getTptuserid().equals(castOther.getTptuserid())))
				&& ((this.getTptgroupid() == castOther.getTptgroupid()) || (this.getTptgroupid() != null
						&& castOther.getTptgroupid() != null && this.getTptgroupid().equals(castOther.getTptgroupid())))
				&& ((this.getTpttemplatename() == castOther.getTpttemplatename())
						|| (this.getTpttemplatename() != null && castOther.getTpttemplatename() != null
								&& this.getTpttemplatename().equals(castOther.getTpttemplatename())))
				&& ((this.getTpttemplate() == castOther.getTpttemplate())
						|| (this.getTpttemplate() != null && castOther.getTpttemplate() != null
								&& this.getTpttemplate().equals(castOther.getTpttemplate())))
				&& ((this.getTptqltask() == castOther.getTptqltask()) || (this.getTptqltask() != null
						&& castOther.getTptqltask() != null && this.getTptqltask().equals(castOther.getTptqltask())))
				&& ((this.getTptscreentype() == castOther.getTptscreentype())
						|| (this.getTptscreentype() != null && castOther.getTptscreentype() != null
								&& this.getTptscreentype().equals(castOther.getTptscreentype())))
				&& ((this.getTptpublicflag() == castOther.getTptpublicflag())
						|| (this.getTptpublicflag() != null && castOther.getTptpublicflag() != null
								&& this.getTptpublicflag().equals(castOther.getTptpublicflag())))
				&& ((this.getTpttemplateobj() == castOther.getTpttemplateobj())
						|| (this.getTpttemplateobj() != null && castOther.getTpttemplateobj() != null
								&& this.getTpttemplateobj().equals(castOther.getTpttemplateobj())))
				&& ((this.getTptfavourite() == castOther.getTptfavourite())
						|| (this.getTptfavourite() != null && castOther.getTptfavourite() != null
								&& this.getTptfavourite().equals(castOther.getTptfavourite())))
				&& ((this.getTptscreenstate() == castOther.getTptscreenstate())
						|| (this.getTptscreenstate() != null && castOther.getTptscreenstate() != null
								&& this.getTptscreenstate().equals(castOther.getTptscreenstate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTptuserid() == null ? 0 : this.getTptuserid().hashCode());
		result = 37 * result + (getTptgroupid() == null ? 0 : this.getTptgroupid().hashCode());
		result = 37 * result + (getTpttemplatename() == null ? 0 : this.getTpttemplatename().hashCode());
		result = 37 * result + (getTpttemplate() == null ? 0 : this.getTpttemplate().hashCode());
		result = 37 * result + (getTptqltask() == null ? 0 : this.getTptqltask().hashCode());
		result = 37 * result + (getTptscreentype() == null ? 0 : this.getTptscreentype().hashCode());
		result = 37 * result + (getTptpublicflag() == null ? 0 : this.getTptpublicflag().hashCode());
		result = 37 * result + (getTpttemplateobj() == null ? 0 : this.getTpttemplateobj().hashCode());
		result = 37 * result + (getTptfavourite() == null ? 0 : this.getTptfavourite().hashCode());
		result = 37 * result + (getTptscreenstate() == null ? 0 : this.getTptscreenstate().hashCode());
		return result;
	}

}
