package com.dcsoft.capmkt.orm;
// Generated Apr 7, 2016 1:42:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserPreferences generated by hbm2java
 */
@Entity
@Table(name = "user_preferences", schema = "public")
public class UserPreferences implements java.io.Serializable {

	private String userid;
	private String preferences;

	public UserPreferences() {
	}

	public UserPreferences(String userid) {
		this.userid = userid;
	}

	public UserPreferences(String userid, String preferences) {
		this.userid = userid;
		this.preferences = preferences;
	}

	@Id

	@Column(name = "userid", unique = true, nullable = false, length = 32)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "preferences")
	public String getPreferences() {
		return this.preferences;
	}

	public void setPreferences(String preferences) {
		this.preferences = preferences;
	}

}
