package com.dcsoft.capmkt.orm;
// Generated Mar 3, 2016 10:39:49 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", schema = "public")
public class User implements java.io.Serializable {

	private String userid;
	private String uname;
	private String upwd;
	private Boolean isactive;

	public User() {
	}

	public User(String userid, String uname, String upwd) {
		this.userid = userid;
		this.uname = uname;
		this.upwd = upwd;
	}

	public User(String userid, String uname, String upwd, Boolean isactive) {
		this.userid = userid;
		this.uname = uname;
		this.upwd = upwd;
		this.isactive = isactive;
	}

	@Id

	@Column(name = "userid", unique = true, nullable = false, length = 32)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "uname", nullable = false, length = 40)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "upwd", nullable = false, length = 200)
	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	@Column(name = "isactive")
	public Boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

}
